const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const {spawn}=require('node:child_process');const path=require('node:path');const fs=require('node:fs/promises');const assert=require('node:assert/strict');
(async()=>{const base=path.resolve(__dirname,'..'),qa=path.join(base,'qa');await fs.mkdir(qa,{recursive:true});const server=spawn(process.execPath,[path.join(base,'serve.mjs')],{env:{...process.env,PORT:'4178'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject)});
let browser;try{browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process']}: {})});const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
for(const width of [320,390,820,1280]){await page.setViewportSize({width,height:900});for(const lang of ['ko','en','zh-Hans','ja','vi','mn','th','ru','id']){
 await page.goto(`http://127.0.0.1:4178/?lang=${lang}`,{waitUntil:'networkidle'});await page.locator('h1').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('header').count(),1);const tooSmall=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(el=>el.getClientRects().length&&[...el.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())&&parseFloat(getComputedStyle(el).fontSize)<16).map(el=>({tag:el.tagName,className:el.className,size:getComputedStyle(el).fontSize})));assert.deepEqual(tooSmall,[]);
 const check=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,bad:[...document.querySelectorAll('body *')].filter(el=>{const r=el.getBoundingClientRect();return r.width&&getComputedStyle(el).position!=='fixed'&&(r.left<-.5||r.right>innerWidth+.5)}).slice(0,8).map(x=>x.className),heading:document.querySelector('h1').innerText}));results.push({page:'home',lang,...check});if(check.scroll>width)console.log('OVERFLOW',width,lang,JSON.stringify(check));
 if(lang==='ko'&&[390,1280].includes(width)){await page.evaluate(async()=>{for(const img of document.images)img.loading='eager';await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})));});await page.screenshot({path:path.join(qa,`home-${width}.png`),fullPage:true});await page.screenshot({path:path.join(qa,`hero-${width}.png`)});}
 await page.goto(`http://127.0.0.1:4178/menu?lang=${lang}`,{waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('lang'),lang);assert.equal(await page.locator('.menu-sections article').count(),32);
 const menu=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,undefined:document.body.innerText.includes('undefined')}));results.push({page:'menu',lang,...menu});if(menu.scroll>width)console.log('MENU OVERFLOW',width,lang,JSON.stringify(menu));assert.equal(menu.undefined,false);
 }}
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4178/?lang=ko');await page.locator('.lang-toggle').click();await page.locator('[data-language="ru"]').click();assert.equal(await page.locator('html').getAttribute('lang'),'ru');await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'ru');await page.locator('.nav-toggle').click();await page.locator('#navigation a[href^="/menu"]').click();await page.locator('.menu-sections article').first().waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'ru');
await page.locator('[data-guide]').click();await page.locator('[data-guide-spice="0"]').click();const choiceCount=await page.locator('.guide-choice').count();assert.ok(choiceCount>0&&choiceCount<=3);await page.locator('[data-guide-choice]').first().click();assert.ok(await page.locator('.guide-item h3[lang="ko"]').count());await page.locator('[data-close]').click();
await page.goto('http://127.0.0.1:4178/menu?lang=th&menu=M006');assert.ok(await page.locator('#detail').evaluate(el=>el.open));await page.locator('[data-close]').click();await page.locator('.filter-panel summary').click();await page.locator('[data-avoid="pork"]').click();assert.ok(await page.locator('.preference-notice').isVisible());await page.locator('.filter-panel summary').click();assert.ok(await page.locator('.preference-notice').isVisible());
await page.screenshot({path:path.join(qa,'menu-390-th.png'),fullPage:true});
const response=await fetch('http://127.0.0.1:4178/prepay',{redirect:'manual'});assert.equal(response.status,307);assert.equal(response.headers.get('location'),'https://gayoungene-prepay.vercel.app/');
await page.goto('http://127.0.0.1:4178/?lang=ko',{waitUntil:'networkidle'});await page.evaluate(async()=>{for(const img of document.images){img.loading='eager';}await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})));});await page.locator('footer').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(qa,'footer-390.png')});const broken=await page.evaluate(()=>[...document.images].filter(x=>!x.naturalWidth).map(x=>x.src));assert.deepEqual(broken,[]);
await fs.writeFile(path.join(qa,'browser-results.json'),JSON.stringify({results,errors,broken,guideChoices:choiceCount,prepayRedirect:response.status,completedAt:new Date().toISOString()},null,2));console.log('BROWSER RESULTS',JSON.stringify({checks:results.length,overflow:results.filter(x=>x.scroll>x.width),errors,broken,guideChoices:choiceCount,fontLoaded:await page.evaluate(()=>document.fonts.check('700 32px Aggro'))}));assert.deepEqual(errors,[]);assert.equal(results.filter(x=>x.scroll>x.width).length,0);
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
