import {qaContent} from './qa-content.js';
import {content,languages} from './content.js';
import {extras} from './extras.js';
import {characters} from './characters.js';
import {assets} from './asset-state.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved;try{saved=localStorage.getItem('gayoungene.language')}catch{}
const query=new URLSearchParams(location.search);let lang=languages[query.get('lang')]?query.get('lang'):languages[saved]?saved:'ko';
const site=document.querySelector('#site');let observer;let ribbonPaused=false;
const ribbonIcon=()=>ribbonPaused?'<path d="m7 4 12 8-12 8Z"/>':'<path d="M6 4h4v16H6zm8 0h4v16h-4z"/>';
const textLines=s=>esc(s).replaceAll('\n','<br> ');
function render(){
 const q=qaContent[lang],t=content[lang],x=extras[lang],c=characters[lang],mallang=Boolean(assets['mallang-gayoung.png']),poster=Boolean(assets['mallang-poster.jpg']),menu=`/menu?lang=${lang}`,lines=k=>textLines(t[k]);
 const ribbonText=[t.ribbonA,t.ribbonB,t.ribbonC,'GAYOUNGENE'];
 const ribbonGroup='<div class="ribbon-group">'+ribbonText.map(word=>'<span>'+esc(word)+'</span><i>✳</i>').join('')+'</div>';
 document.documentElement.lang=lang;document.title=`가영이네 · Gayoungene | ${t.heroA} ${t.heroB}`;
 document.querySelector('.skip').textContent=t.skip;
 document.querySelector('meta[name="description"]').content=t.metaDescription;
 document.querySelector('meta[property="og:title"]').content=document.title;
 document.querySelector('meta[property="og:description"]').content=t.metaDescription;
 site.innerHTML=`<header class="header"><a class="brand" href="/?lang=${lang}" aria-label="${esc(t.home)}"><img src="/assets/logo.png" width="1417" height="502" alt="가영이네 Gayoungene"></a><nav id="navigation" aria-label="${esc(t.nav)}"><a href="#story">${t.story}</a><a href="#food">${t.food}</a><a href="${menu}">${t.find}</a><a href="/prepay">${t.prepay}</a><a href="#visit">${t.visit}</a><a href="#business">${q.contactNav}</a></nav><div class="header-actions"><button class="lang-toggle" aria-expanded="false" aria-controls="languages">◎ <span>${languages[lang]}</span> <span aria-hidden="true">⌄</span></button><button class="nav-toggle" aria-controls="navigation" aria-expanded="false" aria-label="${esc(t.nav)}">${q.navMenu}</button></div><div id="languages" class="language-panel" hidden role="group" aria-label="${esc(t.language)}">${Object.entries(languages).map(([k,n])=>`<button lang="${k}" data-language="${k}" aria-pressed="${k===lang}">${n}</button>`).join('')}</div></header>
 <main id="main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">${esc(t.heroEyebrow)}</p><h1>${t.heroA}<br><span>${t.heroB}</span></h1><p class="hero-intro">${lines('heroText')}</p><div class="actions"><a class="button primary" href="#story">${t.storyCta} <span>↘</span></a><a class="text-link" href="${menu}">${t.menuCta} ↗</a></div><p class="hero-note"><span class="small-star" aria-hidden="true">✳</span> SEOUL, SUYU · EST. 2022</p></div><figure class="hero-art"><div class="arch greeting"><img src="${mallang?'/assets/mallang-gayoung.png':'/assets/logo.png'}" width="${mallang?1212:1417}" height="${mallang?1298:502}" fetchpriority="high" alt="${mallang?esc(c.mallangAlt):'가영이네 Gayoungene'}"></div><span class="hero-stamp" aria-hidden="true"><span>MADE WITH</span><b>마음</b></span></figure></section>
 <div id="brand-ribbon" class="ribbon${ribbonPaused?' is-paused':''}"><p class="visually-hidden">${esc(ribbonText.join(' · '))}</p><div class="ribbon-viewport" aria-hidden="true"><div class="ribbon-track">${ribbonGroup}${ribbonGroup}</div></div><button class="ribbon-toggle" type="button" data-ribbon-toggle aria-label="${esc(ribbonPaused?t.playMotion:t.pauseMotion)}" title="${esc(ribbonPaused?t.playMotion:t.pauseMotion)}" aria-pressed="${ribbonPaused}"><svg viewBox="0 0 24 24" aria-hidden="true">${ribbonIcon()}</svg></button></div>
 <section id="story" class="section wrap"><div class="section-heading reveal"><p class="eyebrow">${esc(t.storyEyebrow)}</p><h2>${lines('storyTitle')}</h2></div><div class="story-grid"><figure class="photo-frame reveal"><img src="/assets/storefront-2022.jpg" width="2047" height="2048" loading="lazy" alt="${esc(t.openingCaption)}"><figcaption>${t.openingCaption}</figcaption><span class="photo-label" aria-hidden="true">${esc(t.openingLabel)}</span></figure><div class="story-copy reveal"><p class="lead">${t.storyLead}</p><ol class="timeline">${[['2012','year1'],['2022','year2'],['2024','year3']].map(([y,k])=>`<li><b>${y}</b><p>${t[k]}</p></li>`).join('')}</ol><a href="https://blog.naver.com/gayoungene/223236981135" target="_blank" rel="noopener noreferrer" class="text-link">${x.blog} ↗</a></div></div></section>
 <section class="handmade"><div class="wrap handmade-grid"><div class="reveal"><p class="eyebrow">${esc(t.handEyebrow)}</p><h2>${lines('handTitle')}</h2><p>${t.handText}</p></div><div class="handmade-photo reveal"><img src="/menu/assets/menu/M018.jpg" width="1280" height="960" loading="lazy" alt="${esc(t.dish2)}"><span class="handwritten">${esc(t.handCaption)}</span></div></div></section>
 <section class="section wrap logo-story"><div class="logo-card reveal"><img src="/assets/logo.png" width="1417" height="502" loading="lazy" alt="가영이네 공식 로고"><p>${esc(t.logoCaption)}</p><svg viewBox="0 0 100 45" aria-hidden="true"><path d="M3 21Q29 5 42 25T95 14M81 12l15 1-5 14" fill="none" stroke="currentColor" stroke-width="2"/></svg></div><div class="reveal"><p class="eyebrow">${esc(t.logoEyebrow)}</p><h2>${lines('logoTitle')}</h2><p>${t.logoText}</p>${assets['mother-daughter.jpg']?`<figure class="portrait"><img src="/assets/mother-daughter.jpg" width="2048" height="2048" loading="lazy" alt="${esc(t.portraitCaption)}"><figcaption>${t.portraitCaption}</figcaption></figure>`:''}</div></section>
 <section class="learning section"><div class="wrap"><div class="section-heading reveal"><p class="eyebrow">${esc(t.learningEyebrow)}</p><h2>${textLines(x.learningTitle)}</h2><p>${x.learningText}</p></div>${assets['learning-wall.jpg']?`<figure class="learning-photo reveal"><img src="/assets/learning-wall.jpg" width="2010" height="1132" loading="lazy" alt="${esc(x.certAlt)}"><figcaption>${x.certCaption}</figcaption></figure>`:''}<div class="proof-grid"><article class="reveal"><span>01</span><h3>${x.educationTitle}</h3><p>${x.educationText}</p></article><article class="reveal"><span>02</span><h3>${x.trademarkTitle}</h3><p>${x.trademarkText}</p></article></div></div></section>
 <section id="food" class="section wrap"><div class="food-heading reveal"><div><p class="eyebrow">${esc(t.foodEyebrow)}</p><h2>${lines('foodTitle')}</h2></div><p>${t.foodText}</p></div><div class="food-grid">${[['M006','dish1','dishText1'],['M018','dish2','dishText2'],['M016','dish3','dishText3']].map(([id,k,desc],i)=>`<a class="food-card reveal" href="${menu}&dish=${id}#dish-${id}"><div class="food-image"><img src="/menu/assets/menu/${id}.jpg" width="1280" height="960" loading="lazy" alt="${esc(t[k])}"></div><div class="food-card-heading"><h3>${t[k]}</h3><span aria-hidden="true">↗</span></div><p>${t[desc]}</p></a>`).join('')}</div><div class="center-actions"><a class="button primary" href="${menu}">${t.find} <span>→</span></a></div></section>
 <section class="welcome"><div class="wrap welcome-grid"><div class="reveal"><p class="eyebrow">${esc(t.welcomeEyebrow)}</p><h2>${lines('welcomeTitle')}</h2><p>${t.welcomeText}</p><a class="button outline" href="${menu}">${t.find} →</a><div class="hello" aria-hidden="true">Hello! 你好! こんにちは!</div></div></div></section>
 <section id="characters" class="section wrap character-story"><div class="section-heading reveal"><p class="eyebrow">${esc(t.charactersEyebrow)}</p><h2>${t.charactersTitle}</h2><p>${t.charactersText}</p></div><div class="character-grid">${[["mallang","mallang-gayoung.png"],["rabbit","rabbit-companion.png"]].map(([key,file])=>`<article class="character-card reveal" aria-labelledby="${key}-name">${assets[file]?`<div class="character-image"><img src="/assets/${file}" loading="lazy" alt="${esc(c[key+"Alt"])}"></div>`:""}<div class="character-copy"><h3 id="${key}-name">${esc(c[key+"Name"])}</h3><p>${esc(c[key+"Text"])}</p></div></article>`).join("")}</div>${poster?`<figure class="poster-archive reveal"><img src="/assets/mallang-poster.jpg" width="1274" height="1984" loading="lazy" alt="${esc(c.posterAlt)}"><figcaption><p>${esc(c.posterAlt)}</p><p class="poster-note">${x.sinceNote}</p></figcaption></figure>`:""}</section>
 <section class="event-band"><div class="wrap event-inner"><div><p class="eyebrow">${esc(t.eventEyebrow)}</p><h2>${textLines(x.eventTitle)}</h2><p>${x.eventText}</p><small>${x.eventNote}</small></div><a class="button outline" href="tel:050714772825">${t.call} ↗</a></div></section>
 <section id="business" class="section business-section"><div class="wrap"><p class="eyebrow">${q.contactNav}</p><h2>${q.contactTitle}</h2><p class="business-intro">${q.contactIntro}</p><p>${q.contactText}</p><div class="actions"><a class="button primary" href="tel:050714772825">${q.contactCta} ↗</a><a class="text-link" href="#visit">${q.hoursCta} ↓</a></div><p class="business-phone">0507-1477-2825</p></div></section>
 <section id="visit" class="section wrap"><p class="eyebrow reveal">${esc(t.visitEyebrow)}</p><h2 class="reveal">${lines('visitTitle')}</h2><div class="visit-grid"><div class="visit-address"><p class="address">${t.address}</p>${lang==='ko'?'':'<p lang="ko">서울 강북구 오패산로 397 1층</p>'}<div class="actions"><a class="button primary" href="https://maps.app.goo.gl/GWxDLkitoXx6AJhC7" target="_blank" rel="noopener noreferrer">${t.directions} ↗</a><a class="text-link" href="tel:050714772825">0507-1477-2825</a></div><a class="review-link" href="https://maps.app.goo.gl/GWxDLkitoXx6AJhC7" target="_blank" rel="noopener noreferrer">${t.review} ↗</a></div><div class="hours"><h3>${t.hoursTitle}</h3><p>${t.weekdays}</p><p>${t.weekends}</p><p class="closed">${t.closed}</p><p class="small">${t.hoursNote}</p></div></div></section>
 <section class="prepay-strip"><div class="wrap"><div><h2>${lines('prepayTitle')}</h2><p>${t.prepayText}</p></div><a class="button dark" href="/prepay">${t.prepayCta} ↗</a></div></section></main>
 <footer class="footer wrap"><a href="/?lang=${lang}" aria-label="${esc(t.home)}"><img src="/assets/logo.png" width="1417" height="502" alt="가영이네 Gayoungene"></a><p>${t.footer}</p><div class="footer-bottom"><span>© ${new Date().getFullYear()} GAYOUNGENE</span><span>SEOUL, SOUTH KOREA</span><a href="tel:050714772825">0507-1477-2825</a></div></footer>`;
 observer?.disconnect();if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('will-reveal');observer.observe(el)});}
}
site.addEventListener('click',e=>{
 const ribbonToggle=e.target.closest('[data-ribbon-toggle]');if(ribbonToggle){ribbonPaused=!ribbonPaused;document.querySelector('.ribbon').classList.toggle('is-paused',ribbonPaused);const label=content[lang][ribbonPaused?'playMotion':'pauseMotion'];ribbonToggle.setAttribute('aria-pressed',String(ribbonPaused));ribbonToggle.setAttribute('aria-label',label);ribbonToggle.title=label;ribbonToggle.querySelector('svg').innerHTML=ribbonIcon();return;}
 const language=e.target.closest('[data-language]');if(language){const y=scrollY;lang=language.dataset.language;try{localStorage.setItem('gayoungene.language',lang)}catch{}const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);render();document.querySelector('.lang-toggle').focus();scrollTo(0,y);return;}
 const langToggle=e.target.closest('.lang-toggle');if(langToggle){const panel=document.querySelector('#languages');panel.hidden=!panel.hidden;langToggle.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)panel.querySelector('[aria-pressed="true"]').focus();return;}
 const navToggle=e.target.closest('.nav-toggle');if(navToggle){const nav=document.querySelector('#navigation'),open=navToggle.getAttribute('aria-expanded')!=='true';navToggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);return;}
 if(e.target.closest('#navigation a')){document.querySelector('#navigation').classList.remove('open');document.querySelector('.nav-toggle').setAttribute('aria-expanded','false');}
});
document.addEventListener('click',e=>{if(!e.target.closest('.language-panel,.lang-toggle')){document.querySelector('#languages').hidden=true;document.querySelector('.lang-toggle').setAttribute('aria-expanded','false')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const panel=document.querySelector('#languages');if(!panel.hidden){panel.hidden=true;document.querySelector('.lang-toggle').setAttribute('aria-expanded','false');document.querySelector('.lang-toggle').focus()}document.querySelector('#navigation').classList.remove('open');document.querySelector('.nav-toggle').setAttribute('aria-expanded','false')}});
render();
