// Descriptions and accessible labels for the approved individual character assets.
const keys = ['mallangName', 'mallangText', 'mallangAlt', 'rabbitName', 'rabbitText', 'rabbitAlt', 'posterAlt'];
const rows = {
  ko: ['말랑 가영이', '주황빛 머리와 앞치마, 밝은 미소로 반갑게 맞이하는 말랑 가영이예요.', '주황빛 머리와 앞치마 차림으로 손을 들어 인사하는 말랑 가영이의 전신', '짝꿍 토끼', '말랑 가영이 곁에서 손을 흔들며 인사하는 토끼 친구예요. 접힌 귀와 주황빛 앞치마를 찾아보세요.', '한쪽 귀가 접힌 크림색 짝꿍 토끼가 주황빛 앞치마를 입고 손을 흔드는 전신', '가영이네 매장에 사용하는 원본 말랑 가영이 포스터'],
  en: ['Mallang Gayoung', 'With orange hair, an orange apron and a bright smile, Mallang Gayoung gives you a warm welcome.', 'Full-body Mallang Gayoung with orange hair and an orange apron, raising a hand in greeting', 'Rabbit Companion', 'Our rabbit friend waves hello beside Mallang Gayoung. Look for the folded ear and orange apron.', 'Full-body cream-colored rabbit with one folded ear and an orange apron, waving hello', 'Original Mallang Gayoung poster used in the Gayoungene shop'],
  'zh-Hans': ['软萌佳映', '橙色头发、橙色围裙和灿烂笑容，软萌佳映热情地欢迎你。', '橙色头发、穿橙色围裙的软萌佳映举手问候的全身形象', '兔子伙伴', '兔子伙伴在软萌佳映身旁挥手问好。看看它折下的一只耳朵和橙色围裙吧。', '一只耳朵折下、穿橙色围裙的奶油色兔子伙伴挥手问候的全身形象', '佳映家店内使用的软萌佳映原版海报'],
  ja: ['マランカヨン', 'オレンジ色の髪とエプロン、明るい笑顔でお迎えするマランカヨンです。', 'オレンジ色の髪とエプロンのマランカヨンが手を上げて挨拶する全身の姿', '相棒のうさぎ', 'マランカヨンのそばで手を振るうさぎの友だち。折れた片耳とオレンジ色のエプロンが目印です。', '片耳が折れたクリーム色のうさぎがオレンジ色のエプロンを着て手を振る全身の姿', 'カヨンイネの店内で使われているマランカヨンのオリジナルポスター'],
  vi: ['Mallang Gayoung', 'Với mái tóc cam, tạp dề cam và nụ cười tươi, Mallang Gayoung vui vẻ chào đón bạn.', 'Toàn thân Mallang Gayoung với tóc cam và tạp dề cam, giơ tay chào', 'Bạn Thỏ', 'Bạn Thỏ vẫy tay chào bên cạnh Mallang Gayoung. Hãy tìm chiếc tai cụp và tạp dề cam nhé.', 'Toàn thân bạn thỏ màu kem với một tai cụp, mặc tạp dề cam và vẫy tay chào', 'Áp phích Mallang Gayoung gốc được sử dụng tại quán Gayoungene'],
  mn: ['Маллан Гаён', 'Улбар шар үстэй, улбар шар хормогчтой Маллан Гаён таныг гэрэлтсэн инээмсэглэлээр угтана.', 'Улбар шар үстэй, улбар шар хормогчтой Маллан Гаён гараа өргөн мэндчилж буй бүтэн биеийн дүрс', 'Туулай найз', 'Маллан Гаёны хажууд туулай найз нь гараа даллан мэндчилнэ. Нугарсан нэг чих, улбар шар хормогчийг нь хараарай.', 'Нэг чих нь нугарсан, улбар шар хормогчтой цайвар шаргал туулай гараа даллаж буй бүтэн биеийн дүрс', 'Гаёнэнэ дэлгүүрт ашигладаг Маллан Гаёны эх зурагт хуудас'],
  th: ['มัลลัง กายอง', 'มัลลัง กายอง ผมสีส้มและผ้ากันเปื้อนสีส้ม พร้อมต้อนรับคุณด้วยรอยยิ้มสดใส', 'ภาพเต็มตัวของมัลลัง กายอง ผมสีส้ม สวมผ้ากันเปื้อนสีส้ม ยกมือทักทาย', 'เพื่อนกระต่าย', 'เพื่อนกระต่ายโบกมือทักทายอยู่ข้างมัลลัง กายอง ลองมองหาหูพับข้างหนึ่งและผ้ากันเปื้อนสีส้มนะ', 'ภาพเต็มตัวของกระต่ายสีครีม หูพับข้างหนึ่ง สวมผ้ากันเปื้อนสีส้มและโบกมือทักทาย', 'โปสเตอร์มัลลัง กายองต้นฉบับที่ใช้ในร้านกายองอีเน'],
  ru: ['Маллан Гаён', 'Оранжевые волосы, оранжевый фартук и светлая улыбка — Маллан Гаён рада вас приветствовать.', 'Маллан Гаён в полный рост, с оранжевыми волосами и в оранжевом фартуке, поднимает руку в знак приветствия', 'Друг-кролик', 'Друг-кролик машет вам лапкой рядом с Маллан Гаён. Узнать его легко по загнутому уху и оранжевому фартуку.', 'Кремовый кролик в полный рост с одним загнутым ухом и в оранжевом фартуке машет лапкой', 'Оригинальный плакат с Маллан Гаён, используемый в кафе Gayoungene'],
  id: ['Mallang Gayoung', 'Dengan rambut oranye, celemek oranye, dan senyum cerah, Mallang Gayoung menyambut Anda dengan hangat.', 'Mallang Gayoung seluruh badan, berambut oranye dan memakai celemek oranye, mengangkat tangan untuk menyapa', 'Sahabat Kelinci', 'Sahabat kelinci melambaikan tangan di samping Mallang Gayoung. Kenali telinga yang terlipat dan celemek oranyenya.', 'Kelinci berwarna krem seluruh badan dengan satu telinga terlipat dan celemek oranye, melambaikan tangan', 'Poster asli Mallang Gayoung yang digunakan di kedai Gayoungene'],
};
export const characters = Object.fromEntries(Object.entries(rows).map(([lang, values]) => [lang, Object.fromEntries(keys.map((key, i) => [key, values[i]]))]));
