export const languages={
  "ko": "한국어",
  "en": "English",
  "zh-Hans": "中文",
  "ja": "日本語",
  "vi": "Tiếng Việt",
  "mn": "Монгол",
  "th": "ไทย",
  "ru": "Русский",
  "id": "Indonesia"
};
export const content={
  "ko": {
    "story": "우리 이야기",
    "food": "메뉴 소개",
    "find": "나에게 맞는 메뉴",
    "prepay": "선결제 신청",
    "visit": "오시는 길",
    "heroA": "엄마의 손맛,",
    "heroB": "모녀가 차리는 한 끼.",
    "heroText": "2012년부터 분식을 만들어온 엄마와\n가게의 이름과 얼굴을 그려낸 딸 가영.\n두 사람이 함께 요리하고 맞이하는 수유의 수제 분식집입니다.",
    "storyCta": "모녀의 이야기 읽기",
    "menuCta": "메뉴와 가격 보기",
    "storyTitle": "엄마가 시작한 꿈,\n모녀가 함께 연 가게.",
    "storyLead": "2012년, 약수동 분식집의 직원으로 시작한 엄마는 약 10년간 주방에서 손맛을 쌓았습니다. 자기 가게를 열려던 엄마 곁에 딸 가영이 함께했고, 이름과 로고부터 공간까지 손수 준비했습니다. 2022년 2월 12일, 수유에 가영이네의 문을 열었습니다.",
    "year1": "약수동 분식집 직원으로 시작한 엄마의 조리 경험.",
    "year2": "엄마의 창업에 딸이 함께하며, 2월 12일 수유에 가영이네 개업.",
    "year3": "편안한 한 끼를 위해, 여름에 옆 공간까지 매장을 확장.",
    "handTitle": "속을 채우는 일부터,\n손님을 맞는 일까지.",
    "handText": "김밥 속재료를 손질하고, 튀김 재료를 준비합니다. 엄마는 핵심 소스를 맡고, 딸 가영도 조리와 주문, 손님맞이와 정리를 함께합니다. 익숙한 분식 한 접시를 위해 모녀가 함께 움직이는 일. 가영이네가 매일 이어가는 방식입니다.",
    "logoTitle": "이름은 딸,\n얼굴은 엄마.",
    "logoText": "가게를 준비하던 가영은 엄마의 사진을 보고 로고를 직접 그렸습니다. 그래서 가영이네는 딸의 이름으로 불리고, 엄마의 얼굴로 손님을 맞습니다. 함께 만든 가게라는 이야기가 이름과 얼굴에 고스란히 담겨 있습니다.",
    "portraitCaption": "가영이네를 함께 만들어가는 가영과 어머니",
    "openingCaption": "2022년 문을 열었을 때의 가영이네. 사진 속 메뉴 가격은 당시의 기록입니다.",
    "foodTitle": "오늘은 어떤 분식이\n생각나세요?",
    "foodText": "달콤하고 매콤한 떡볶이, 속을 넉넉히 채운 김밥, 바삭한 튀김. 사진을 누르면 메뉴의 가격과 설명을 자세히 볼 수 있습니다.",
    "dish1": "1988 옛날떡볶이",
    "dish2": "가영이김밥",
    "dish3": "수제 오징어튀김",
    "dishText1": "떡과 어묵에 달콤하고 매콤한 소스. 익숙해서 더 반가운 한 접시.",
    "dishText2": "밥은 가볍게, 달걀과 채소는 넉넉하게. 속을 채워 든든하게 말았습니다.",
    "dishText3": "쫄깃한 오징어를 바삭하게. 떡볶이 곁에도, 그 자체로도 반가운 맛.",
    "welcomeTitle": "처음 만나는 분식도,\n편하게 고르세요.",
    "welcomeText": "사진과 재료, 맵기를 자신의 언어로 살펴보세요. 메뉴를 고르면 한국어 이름을 직원에게 보여줄 수 있습니다. 오늘의 한 끼를 고르는 시간이 조금 더 편안하도록 준비했습니다.",
    "charactersTitle": "반가운 마음을 닮은 두 친구",
    "charactersText": "주황빛 앞치마를 두른 말랑 가영이와 짝꿍 토끼. 가영이네의 밝은 인사를 전하는 친구들을 만나보세요.",
    "visitTitle": "수유에서,\n따뜻한 한 끼로 만나요.",
    "address": "서울특별시 강북구 오패산로 397, 1층",
    "hoursTitle": "영업시간",
    "weekdays": "월·수·목·금 11:00–14:00 / 16:00–22:00",
    "weekends": "토·일·공휴일 16:00–22:00",
    "closed": "화요일 정기휴무",
    "hoursNote": "방문 전 영업시간을 확인해 주세요. 매장 사정에 따라 달라질 수 있습니다.",
    "directions": "지도에서 길찾기",
    "call": "매장으로 전화하기",
    "review": "손님들의 방문 후기 읽기 · Google 지도",
    "prepayTitle": "자주 만나는 사이,\n한 끼를 더 편하게.",
    "prepayText": "자주 찾아주시는 손님을 위한 선결제 안내입니다. 신청서를 작성한 뒤 매장의 결제 확인을 거쳐 포인트가 충전됩니다. 신청만으로 결제나 충전이 완료되지는 않습니다.",
    "prepayCta": "선결제 신청서 열기",
    "footer": "엄마의 손맛으로 시작해, 모녀의 하루로 이어지는 가영이네.",
    "language": "언어 선택",
    "nav": "메뉴 열기",
    "skip": "본문으로 바로가기",
    "close": "닫기",
    "home": "공식 홈페이지",
    "heroEyebrow": "수유의 수제 분식집 · GAYOUNGENE",
    "storyEyebrow": "01 / 모녀의 이야기",
    "handEyebrow": "함께 일하는 오늘",
    "logoEyebrow": "가게의 이름과 얼굴",
    "learningEyebrow": "배움을 이어가는 가게",
    "foodEyebrow": "02 / 가영이네 메뉴",
    "welcomeEyebrow": "03 / 당신의 언어로",
    "charactersEyebrow": "말랑 가영이와 짝꿍 토끼",
    "eventEyebrow": "매장 소식",
    "visitEyebrow": "04 / 찾아오시는 길",
    "openingLabel": "수유에서 시작한 2022년",
    "handCaption": "함께 준비하는 오늘의 한 끼",
    "logoCaption": "가영이가 그린 엄마의 얼굴",
    "pauseMotion": "띠 문구 움직임 멈추기",
    "playMotion": "띠 문구 움직임 재생",
    "ribbonA": "엄마의 손맛",
    "ribbonB": "딸의 손길",
    "ribbonC": "함께 차리는 한 끼",
    "metaDescription": "2012년부터 분식을 만들어온 엄마와 가게의 이름과 얼굴을 그려낸 딸 가영. 두 사람이 함께 요리하고 맞이하는 수유의 수제 분식집입니다."
  },
  "en": {
    "story": "Our story",
    "food": "Our food",
    "find": "Find your menu",
    "prepay": "Prepay",
    "visit": "Visit us",
    "heroA": "Mom’s cooking.",
    "heroB": "Made together.",
    "heroText": "A mother who has cooked Korean bunsik since 2012.\nA daughter, Gayoung, who gave the shop its name and face.\nTogether, we cook and welcome you in Suyu, Seoul.",
    "storyCta": "Meet mother and daughter",
    "menuCta": "See the menu & prices",
    "storyTitle": "A mother’s dream.\nA shop they opened together.",
    "storyLead": "Mom began working at a bunsik shop in Yaksu-dong in 2012, building her cooking skills over about ten years. When she set out to open her own place, Gayoung joined her. They prepared the space, name and logo themselves. On February 12, 2022, Gayoungene opened in Suyu.",
    "year1": "Mom began cooking as an employee at a bunsik shop in Yaksu-dong.",
    "year2": "Mother and daughter opened Gayoungene in Suyu on February 12.",
    "year3": "Expanded next door that summer to give guests more room to enjoy a meal.",
    "handTitle": "From filling the rolls\nto welcoming you in.",
    "handText": "We prepare gimbap fillings and ingredients for our fried dishes by hand. Mom makes the key sauces; Gayoung shares the cooking, orders, service and cleanup. Two people working together behind a familiar plate of Korean comfort food. This is everyday life at Gayoungene.",
    "logoTitle": "The daughter’s name.\nThe mother’s face.",
    "logoText": "While preparing to open, Gayoung drew the logo by hand from a photograph of her mother. The shop carries the daughter’s name and welcomes you with the mother’s face. Both are part of the place they made together.",
    "portraitCaption": "Gayoung and her mother, the people behind Gayoungene",
    "openingCaption": "Gayoungene when it opened in 2022. Menu prices in this photograph are historical.",
    "foodTitle": "What are you\nin the mood for?",
    "foodText": "Sweet and spicy tteokbokki, generously filled gimbap, or something crisp from the fryer. Tap a photo to see the dish, price and details.",
    "dish1": "1988 Classic Tteokbokki",
    "dish2": "Gayoung Gimbap",
    "dish3": "Hand-prepared squid fritters",
    "dishText1": "Tteok and fish cakes in a sweet, spicy sauce. A familiar plate of Korean comfort.",
    "dishText2": "Less rice, plenty of egg and vegetables. A generously filled roll for your meal.",
    "dishText3": "Tender, chewy squid with a crisp coating. Enjoy it alongside tteokbokki or on its own.",
    "welcomeTitle": "New to Korean bunsik?\nMake yourself at home.",
    "welcomeText": "Browse photos, ingredients and spice levels in your language. Once you choose, show the Korean dish name to our staff. A little help to make choosing your meal feel easier.",
    "charactersTitle": "Two little friends, one warm welcome",
    "charactersText": "Meet Mallang Gayoung and her rabbit companion in their orange aprons. They bring Gayoungene’s cheerful hello to life.",
    "visitTitle": "Find us in Suyu.\nStay for a meal.",
    "address": "1F, 397 Opaesan-ro, Gangbuk-gu, Seoul",
    "hoursTitle": "Opening hours",
    "weekdays": "Mon, Wed, Thu, Fri 11:00–14:00 / 16:00–22:00",
    "weekends": "Sat, Sun & public holidays 16:00–22:00",
    "closed": "Closed Tuesdays",
    "hoursNote": "Please check our hours before visiting. They may change with shop circumstances.",
    "directions": "Get directions",
    "call": "Call the shop",
    "review": "Read guest reviews · Google Maps",
    "prepayTitle": "For familiar faces\nand everyday meals.",
    "prepayText": "Our prepay service is available for returning guests. After you apply, the shop confirms payment before adding points. Submitting the form does not complete a payment or add points.",
    "prepayCta": "Open prepay form · Korean",
    "footer": "A mother’s cooking. A daughter by her side. This is Gayoungene.",
    "language": "Choose language",
    "nav": "Open navigation",
    "skip": "Skip to content",
    "close": "Close",
    "home": "Official home",
    "heroEyebrow": "KOREAN COMFORT FOOD · SUYU, SEOUL",
    "storyEyebrow": "01 / MOTHER & DAUGHTER",
    "handEyebrow": "MADE TOGETHER, EVERY DAY",
    "logoEyebrow": "THE NAME & THE FACE",
    "learningEyebrow": "ALWAYS LEARNING",
    "foodEyebrow": "02 / FIND YOUR FAVORITE",
    "welcomeEyebrow": "03 / CHOOSE IN YOUR LANGUAGE",
    "charactersEyebrow": "MEET OUR LITTLE FRIENDS",
    "eventEyebrow": "AT THE SHOP",
    "visitEyebrow": "04 / COME ON OVER",
    "openingLabel": "OUR BEGINNING IN SUYU, 2022",
    "handCaption": "Made together, every day.",
    "logoCaption": "Mom, drawn by Gayoung.",
    "pauseMotion": "Pause scrolling words",
    "playMotion": "Resume scrolling words",
    "ribbonA": "Mom’s recipes",
    "ribbonB": "A daughter’s touch",
    "ribbonC": "Made together",
    "metaDescription": "A mother who has cooked Korean bunsik since 2012. A daughter, Gayoung, who gave the shop its name and face. Together, we cook and welcome you in Suyu, Seoul."
  },
  "zh-Hans": {
    "story": "我们的故事",
    "food": "美味菜单",
    "find": "寻找适合的菜品",
    "prepay": "预付款申请",
    "visit": "到店指南",
    "heroA": "妈妈的手艺，",
    "heroB": "母女一起准备的一餐。",
    "heroText": "从2012年开始做韩式小吃的妈妈，\n为店铺取名、画下标志的女儿佳映。\n在首尔水逾，我们一起下厨，也一起迎接您。",
    "storyCta": "认识这对母女",
    "menuCta": "查看菜单与价格",
    "storyTitle": "妈妈的梦想，\n母女一起开起的小店。",
    "storyLead": "2012年，妈妈开始在药水洞的一家韩式小吃店做员工，用约十年的时间积累厨艺。准备开自己的店时，女儿佳映加入了她。从店名、标志到空间，两人亲手筹备。2022年2月12日，佳映家在水逾开门迎客。",
    "year1": "妈妈在药水洞的韩式小吃店，从员工做起积累厨艺。",
    "year2": "2月12日，母女一起在水逾开了佳映家。",
    "year3": "夏天扩展到隔壁空间，让客人更舒适地享用一餐。",
    "handTitle": "从准备馅料，\n到迎接您的到来。",
    "handText": "我们亲手处理紫菜包饭的馅料，准备炸物的食材。妈妈负责主要酱汁，佳映也一起做菜、接单、招待和收拾。熟悉的一盘韩式小吃背后，是母女一起忙碌的日常。",
    "logoTitle": "店名是女儿，\n标志里的脸是妈妈。",
    "logoText": "筹备开店时，佳映看着妈妈的照片，亲手画下了标志。店铺以女儿的名字命名，用妈妈的笑脸迎客。母女一起开店的故事，就藏在名字与标志里。",
    "portraitCaption": "一起经营佳映家的佳映和妈妈",
    "openingCaption": "2022年开业时的佳映家。照片中的菜单价格是当年的记录。",
    "foodTitle": "今天，\n想吃哪一道韩式小吃？",
    "foodText": "甜辣的炒年糕、馅料丰富的紫菜包饭，还有酥脆的炸物。点击照片，查看菜品价格与详细介绍。",
    "dish1": "1988经典韩式辣炒年糕",
    "dish2": "佳映紫菜包饭",
    "dish3": "手工准备的炸鱿鱼",
    "dishText1": "年糕与鱼饼裹上甜辣酱汁。熟悉的一盘，吃来格外亲切。",
    "dishText2": "少一些米饭，多一些鸡蛋和蔬菜。卷起满满馅料的一餐。",
    "dishText3": "有嚼劲的鱿鱼配上酥脆外衣。搭配炒年糕或单独品尝，都很合适。",
    "welcomeTitle": "第一次尝试韩式小吃，\n也能轻松选择。",
    "welcomeText": "用自己的语言查看照片、食材和辣度。选好后，还可以把韩语菜名出示给店员。我们希望选餐的过程，也能让您感到自在。",
    "charactersTitle": "两个小伙伴，送上一份热情",
    "charactersText": "穿上橙色围裙的软萌佳映和兔子伙伴，带着佳映家的笑容向您打招呼。",
    "visitTitle": "在水逾，\n为您准备一餐。",
    "address": "首尔特别市江北区梧牌山路397号1楼",
    "hoursTitle": "营业时间",
    "weekdays": "周一、三、四、五 11:00–14:00 / 16:00–22:00",
    "weekends": "周六、日及公共假日 16:00–22:00",
    "closed": "每周二休息",
    "hoursNote": "到店前请确认营业时间。时间可能因店内情况而变更。",
    "directions": "查看地图路线",
    "call": "致电店铺",
    "review": "阅读顾客到店评价 · Google地图",
    "prepayTitle": "为常来的您，\n让用餐更方便。",
    "prepayText": "常来店里的客人可以使用预付款服务。填写申请后，店铺确认付款，再充值积分。提交申请并不代表付款或积分充值已经完成。",
    "prepayCta": "打开预付款申请表 · 韩语",
    "footer": "从妈妈的手艺出发，延续在母女一起经营的每一天。这里是佳映家。",
    "language": "选择语言",
    "nav": "打开导航",
    "skip": "跳至正文",
    "close": "关闭",
    "home": "官方网站首页",
    "heroEyebrow": "首尔水逾的韩式小吃店 · GAYOUNGENE",
    "storyEyebrow": "01 / 母女的故事",
    "handEyebrow": "一起经营的每一天",
    "logoEyebrow": "店名与标志",
    "learningEyebrow": "不断学习的小店",
    "foodEyebrow": "02 / 佳映家菜单",
    "welcomeEyebrow": "03 / 用您的语言选择",
    "charactersEyebrow": "认识我们的小伙伴",
    "eventEyebrow": "店内消息",
    "visitEyebrow": "04 / 到店指南",
    "openingLabel": "2022年，从水逾开始",
    "handCaption": "一起准备今天的一餐",
    "logoCaption": "佳映画下的妈妈",
    "pauseMotion": "暂停文字滚动",
    "playMotion": "继续文字滚动",
    "ribbonA": "妈妈的手艺",
    "ribbonB": "女儿的心意",
    "ribbonC": "一起准备的一餐",
    "metaDescription": "从2012年开始做韩式小吃的妈妈， 为店铺取名、画下标志的女儿佳映。 在首尔水逾，我们一起下厨，也一起迎接您。"
  },
  "ja": {
    "story": "私たちの物語",
    "food": "メニュー紹介",
    "find": "メニューを選ぶ",
    "prepay": "前払い申込み",
    "visit": "アクセス",
    "heroA": "お母さんの味を、",
    "heroB": "母と娘の手で。",
    "heroText": "2012年から韓国の軽食を作り続けてきた母。\n店の名前と顔を形にした娘、カヨン。\nソウル・水踰で、一緒に料理を作り、お迎えしています。",
    "storyCta": "母と娘の物語を読む",
    "menuCta": "メニューと価格を見る",
    "storyTitle": "母の夢から、\nふたりのお店へ。",
    "storyLead": "2012年、薬水洞の軽食店で従業員として働き始めた母は、約10年かけて料理の経験を重ねました。自分の店を開こうとした母に、娘カヨンも加わります。名前やロゴ、店内の空間まで自分たちで準備し、2022年2月12日、水踰にカヨンイネをオープンしました。",
    "year1": "薬水洞の軽食店で、母が従業員として料理の経験を積み始める。",
    "year2": "2月12日、母と娘が水踰にカヨンイネをオープン。",
    "year3": "夏、ゆっくり食事を楽しめるよう隣の空間へ拡張。",
    "handTitle": "具材の下ごしらえから、\nお客様のお迎えまで。",
    "handText": "キンパの具材を整え、揚げ物の材料を準備する。母が中心となるソースを作り、カヨンも調理、注文、おもてなし、片付けを担います。なじみのある一皿のために、ふたりで手を動かす。それがカヨンイネの日常です。",
    "logoTitle": "名前は娘。\n顔はお母さん。",
    "logoText": "開店を準備していたカヨンが、母の写真を見ながら手描きしたロゴです。娘の名前で呼ばれ、母の顔でお迎えする店。名前にもロゴにも、ふたりで作ったお店の物語が込められています。",
    "portraitCaption": "カヨンイネを一緒に営むカヨンとお母さん",
    "openingCaption": "2022年の開店当時のカヨンイネ。写真のメニュー価格は当時のものです。",
    "foodTitle": "今日はどの味に\nしましょうか。",
    "foodText": "甘辛いトッポッキ、具だくさんのキンパ、サクサクの揚げ物。写真を押すと、価格や料理の説明をご覧いただけます。",
    "dish1": "1988 昔ながらのトッポッキ",
    "dish2": "カヨンキンパ",
    "dish3": "手仕込みのイカ天ぷら",
    "dishText1": "トックと魚の練り物を甘辛いソースで。どこかほっとする、なじみの一皿。",
    "dishText2": "ご飯は少なめ、卵と野菜はたっぷり。具材をしっかり包んだ一本です。",
    "dishText3": "歯ごたえのあるイカを、サクッと。トッポッキのお供にも、そのままでも。",
    "welcomeTitle": "初めての韓国軽食も、\n気軽に選べるように。",
    "welcomeText": "写真や食材、辛さを、ご自分の言語でご覧ください。選んだ料理は、韓国語の名前をスタッフに見せられます。今日の一食を選ぶ時間も、少し心地よくなるように。",
    "charactersTitle": "ふたりの小さな仲間がお出迎え",
    "charactersText": "オレンジ色のエプロンを着たマランカヨンとウサギ。カヨンイネの明るい挨拶を届ける仲間たちです。",
    "visitTitle": "水踰で、\n一食をご一緒に。",
    "address": "ソウル特別市江北区梧牌山路397 1階",
    "hoursTitle": "営業時間",
    "weekdays": "月・水・木・金 11:00–14:00 / 16:00–22:00",
    "weekends": "土・日・祝日 16:00–22:00",
    "closed": "火曜定休",
    "hoursNote": "お越しになる前に営業時間をご確認ください。都合により変更する場合があります。",
    "directions": "地図で道順を見る",
    "call": "お店に電話する",
    "review": "お客様の口コミを読む · Googleマップ",
    "prepayTitle": "いつもの顔ぶれに、\nいつもの一食を。",
    "prepayText": "よくお越しくださる方のための前払いサービスです。申込み後、お店で支払いを確認してからポイントが加算されます。申込書の送信だけでは、支払いやチャージは完了しません。",
    "prepayCta": "前払い申込書を開く · 韓国語",
    "footer": "母の味から始まり、母と娘の毎日へ。カヨンイネです。",
    "language": "言語を選択",
    "nav": "メニューを開く",
    "skip": "本文へ移動",
    "close": "閉じる",
    "home": "公式ホーム",
    "heroEyebrow": "ソウル・水踰の韓国軽食店 · GAYOUNGENE",
    "storyEyebrow": "01 / 母と娘の物語",
    "handEyebrow": "一緒に働く毎日",
    "logoEyebrow": "お店の名前と顔",
    "learningEyebrow": "学び続けるお店",
    "foodEyebrow": "02 / カヨンイネのメニュー",
    "welcomeEyebrow": "03 / あなたの言語で",
    "charactersEyebrow": "小さな仲間をご紹介",
    "eventEyebrow": "お店からのお知らせ",
    "visitEyebrow": "04 / アクセス",
    "openingLabel": "2022年、水踰から",
    "handCaption": "今日の一食も、一緒に。",
    "logoCaption": "カヨンが描いた、お母さん。",
    "pauseMotion": "文字の動きを止める",
    "playMotion": "文字の動きを再開する",
    "ribbonA": "お母さんの味",
    "ribbonB": "娘の手仕事",
    "ribbonC": "一緒に作る一食",
    "metaDescription": "2012年から韓国の軽食を作り続けてきた母。 店の名前と顔を形にした娘、カヨン。 ソウル・水踰で、一緒に料理を作り、お迎えしています。"
  },
  "vi": {
    "story": "Câu chuyện",
    "food": "Món ăn",
    "find": "Chọn món phù hợp",
    "prepay": "Đăng ký trả trước",
    "visit": "Ghé thăm",
    "heroA": "Tay nghề của mẹ,",
    "heroB": "bữa ăn hai mẹ con cùng làm.",
    "heroText": "Mẹ làm món ăn Hàn từ năm 2012.\nCon gái Gayoung tạo nên tên gọi và gương mặt của quán.\nTại Suyu, Seoul, hai mẹ con cùng nấu ăn và đón bạn.",
    "storyCta": "Đọc chuyện hai mẹ con",
    "menuCta": "Xem món và giá",
    "storyTitle": "Từ ước mơ của mẹ,\nđến quán của hai mẹ con.",
    "storyLead": "Năm 2012, mẹ bắt đầu làm nhân viên tại một quán ăn Hàn ở Yaksu-dong và tích lũy kinh nghiệm trong khoảng mười năm. Khi mẹ muốn mở quán riêng, Gayoung cùng tham gia. Từ tên gọi, logo đến không gian, hai mẹ con tự tay chuẩn bị. Ngày 12 tháng 2 năm 2022, Gayoungene mở cửa tại Suyu.",
    "year1": "Mẹ bắt đầu tích lũy tay nghề khi làm nhân viên quán ăn ở Yaksu-dong.",
    "year2": "Ngày 12 tháng 2, hai mẹ con mở Gayoungene tại Suyu.",
    "year3": "Mở rộng sang bên cạnh vào mùa hè để khách có thêm không gian dùng bữa.",
    "handTitle": "Từ chuẩn bị nhân cuốn,\nđến đón bạn vào quán.",
    "handText": "Chúng tôi tự sơ chế nhân gimbap và nguyên liệu món chiên. Mẹ phụ trách những loại sốt chính; Gayoung cùng nấu, nhận món, phục vụ và dọn dẹp. Hai mẹ con cùng làm nên một đĩa món Hàn thân thuộc. Đó là mỗi ngày ở Gayoungene.",
    "logoTitle": "Tên của con gái.\nGương mặt của mẹ.",
    "logoText": "Khi chuẩn bị mở quán, Gayoung nhìn ảnh mẹ và tự tay vẽ logo. Quán mang tên con gái, chào đón bạn bằng gương mặt của mẹ. Câu chuyện hai mẹ con cùng gây dựng nằm trong cả tên gọi và hình ảnh ấy.",
    "portraitCaption": "Gayoung và mẹ, hai người cùng làm nên Gayoungene",
    "openingCaption": "Gayoungene khi mở cửa năm 2022. Giá trên ảnh là giá của thời điểm đó.",
    "foodTitle": "Hôm nay,\nbạn muốn ăn món gì?",
    "foodText": "Tteokbokki ngọt cay, gimbap đầy nhân hay món chiên giòn. Chạm vào ảnh để xem giá và giới thiệu từng món.",
    "dish1": "Tteokbokki cổ điển 1988",
    "dish2": "Gimbap Gayoung",
    "dish3": "Mực chiên tự sơ chế",
    "dishText1": "Bánh gạo và chả cá trong sốt ngọt cay. Một đĩa món Hàn thân quen.",
    "dishText2": "Ít cơm hơn, nhiều trứng và rau hơn. Cuộn gimbap đầy đặn cho bữa ăn của bạn.",
    "dishText3": "Mực dai nhẹ trong lớp vỏ giòn. Ăn cùng tteokbokki hoặc thưởng thức riêng.",
    "welcomeTitle": "Lần đầu thử món Hàn?\nCứ thoải mái chọn nhé.",
    "welcomeText": "Xem ảnh, nguyên liệu và độ cay bằng ngôn ngữ của bạn. Khi đã chọn, bạn có thể đưa tên món tiếng Hàn cho nhân viên xem. Một chút hỗ trợ để việc chọn bữa ăn dễ dàng hơn.",
    "charactersTitle": "Hai người bạn nhỏ gửi lời chào ấm áp",
    "charactersText": "Gặp Mallang Gayoung và bạn Thỏ trong chiếc tạp dề cam. Hai người bạn mang lời chào vui tươi của Gayoungene đến với bạn.",
    "visitTitle": "Hẹn bạn ở Suyu,\ncùng một bữa ăn ngon.",
    "address": "Tầng 1, 397 Opaesan-ro, Gangbuk-gu, Seoul",
    "hoursTitle": "Giờ mở cửa",
    "weekdays": "Thứ 2, 4, 5, 6: 11:00–14:00 / 16:00–22:00",
    "weekends": "Thứ 7, CN và ngày lễ: 16:00–22:00",
    "closed": "Nghỉ thứ Ba",
    "hoursNote": "Vui lòng kiểm tra giờ trước khi đến. Giờ mở cửa có thể thay đổi tùy tình hình quán.",
    "directions": "Xem đường đi",
    "call": "Gọi cho quán",
    "review": "Đọc đánh giá của khách · Google Maps",
    "prepayTitle": "Cho những lần quen mặt,\nnhững bữa ăn thường ngày.",
    "prepayText": "Khách thường ghé có thể dùng dịch vụ trả trước. Sau khi bạn gửi đơn, quán xác nhận thanh toán rồi mới nạp điểm. Gửi đơn không có nghĩa là đã thanh toán hoặc được nạp điểm.",
    "prepayCta": "Mở đơn trả trước · tiếng Hàn",
    "footer": "Bắt đầu từ tay nghề của mẹ, tiếp nối trong mỗi ngày hai mẹ con cùng làm. Đó là Gayoungene.",
    "language": "Chọn ngôn ngữ",
    "nav": "Mở điều hướng",
    "skip": "Đến nội dung",
    "close": "Đóng",
    "home": "Trang chính thức",
    "heroEyebrow": "MÓN HÀN Ở SUYU, SEOUL · GAYOUNGENE",
    "storyEyebrow": "01 / CHUYỆN HAI MẸ CON",
    "handEyebrow": "CÙNG LÀM MỖI NGÀY",
    "logoEyebrow": "TÊN GỌI VÀ GƯƠNG MẶT",
    "learningEyebrow": "LUÔN HỌC HỎI",
    "foodEyebrow": "02 / THỰC ĐƠN GAYOUNGENE",
    "welcomeEyebrow": "03 / CHỌN BẰNG NGÔN NGỮ CỦA BẠN",
    "charactersEyebrow": "GẶP NHỮNG NGƯỜI BẠN NHỎ",
    "eventEyebrow": "TIN TỪ QUÁN",
    "visitEyebrow": "04 / GHÉ THĂM CHÚNG TÔI",
    "openingLabel": "BẮT ĐẦU Ở SUYU, 2022",
    "handCaption": "Cùng chuẩn bị bữa ăn mỗi ngày.",
    "logoCaption": "Mẹ, qua nét vẽ của Gayoung.",
    "pauseMotion": "Dừng chữ chuyển động",
    "playMotion": "Tiếp tục chữ chuyển động",
    "ribbonA": "Tay nghề của mẹ",
    "ribbonB": "Bàn tay của con",
    "ribbonC": "Bữa ăn cùng làm",
    "metaDescription": "Mẹ làm món ăn Hàn từ năm 2012. Con gái Gayoung tạo nên tên gọi và gương mặt của quán. Tại Suyu, Seoul, hai mẹ con cùng nấu ăn và đón bạn."
  },
  "mn": {
    "story": "Бидний түүх",
    "food": "Хоолны цэс",
    "find": "Хоолоо сонгох",
    "prepay": "Урьдчилан төлөх",
    "visit": "Биднийг зориорой",
    "heroA": "Ээжийн гарын амт,",
    "heroB": "ээж, охины хамтын зоог.",
    "heroText": "Ээж 2012 оноос солонгос хөнгөн хоол хийж ирсэн.\nОхин Гаён нь газрынхаа нэр, логог бүтээсэн.\nСөүлийн Сүюүд бид хамтдаа хоол хийж, таныг угтдаг.",
    "storyCta": "Ээж, охины түүхийг унших",
    "menuCta": "Хоол, үнэ харах",
    "storyTitle": "Ээжийн мөрөөдлөөс\nхамтдаа нээсэн газар хүртэл.",
    "storyLead": "Ээж 2012 онд Яксү-дон дахь хөнгөн хоолны газарт ажилтнаар орж, арав орчим жил хоол хийх туршлага хуримтлуулжээ. Өөрийн газраа нээхээр болоход нь охин Гаён хамтран зүтгэсэн. Нэр, лого, дотоод орчноо өөрсдөө бэлтгээд, 2022 оны 2-р сарын 12-нд Сүюүд Gayoungene-г нээсэн юм.",
    "year1": "Ээж Яксү-дон дахь хөнгөн хоолны газарт ажиллаж, туршлага хуримтлуулж эхлэв.",
    "year2": "2-р сарын 12-нд ээж, охин хоёр Сүюүд Gayoungene-г нээв.",
    "year3": "Зочдоо тухтай хооллуулахын тулд зун нь хажуугийн талбай руу өргөжив.",
    "handTitle": "Кимбабын шанз бэлтгэхээс\nтаныг угтах хүртэл.",
    "handText": "Бид кимбабын шанз, шарсан хоолны орцыг өөрсдөө бэлтгэдэг. Ээж гол соусуудаа хийж, Гаён хоол хийх, захиалга авах, үйлчлэх, цэвэрлэх ажилд хамт оролцоно. Танил нэг таваг хоолны ард ээж, охин хоёрын хамтын хөдөлмөр бий. Энэ бол Gayoungene-гийн өдөр тутам.",
    "logoTitle": "Нэр нь охиных.\nДүр нь ээжийнх.",
    "logoText": "Газраа нээхээр бэлтгэж байхдаа Гаён ээжийнхээ гэрэл зургийг харан логог гараар зуржээ. Охиныхоо нэртэй энэ газар ээжийнхээ дүрээр таныг угтана. Хамтдаа бүтээсэн газрын түүх нэр, лого хоёрт нь шингэсэн юм.",
    "portraitCaption": "Gayoungene-г хамтдаа авч явдаг Гаён болон ээж нь",
    "openingCaption": "2022 онд нээгдэх үеийн Gayoungene. Зураг дээрх хоолны үнэ тухайн үеийнх.",
    "foodTitle": "Өнөөдөр ямар хоол\nидмээр байна вэ?",
    "foodText": "Амтлаг, халуун ногоотой ттокбокки, дүүрэн шанзтай кимбаб эсвэл шаржигнуур хоол. Зураг дээр дарж үнэ, тайлбарыг үзээрэй.",
    "dish1": "1988 сонгодог Ттокбокки",
    "dish2": "Гаён Гимбап",
    "dish3": "Өөрсдөө бэлтгэсэн шарсан кальмар",
    "dishText1": "Тток, загасан котлетыг амтлаг, халуун ногоотой соустай. Солонгосын танил нэг таваг хоол.",
    "dishText2": "Будаа багатай, өндөг ногоо ихтэй. Шанзаар дүүрэн нэг ороомог.",
    "dishText3": "Зөөлөн зажлууртай кальмар, шаржигнуур бүрхүүл. Ттокбоккитой хамт эсвэл дангаар нь амтлаарай.",
    "welcomeTitle": "Солонгос хоол анх удаа юу?\nТавтай сонгоорой.",
    "welcomeText": "Зураг, орц, халуун ногооны хэмжээг өөрийн хэлээр үзээрэй. Сонгосон хоолныхоо солонгос нэрийг ажилтанд харуулж болно. Өнөөдрийн хоолоо сонгоход тань бага ч болов туслахыг хүссэн юм.",
    "charactersTitle": "Хоёр бяцхан найзын халуун дотно мэндчилгээ",
    "charactersText": "Улбар шар хормогчтой Маллан Гаён, туулай найзтай нь танилцаарай. Тэд Gayoungene-гийн баяр хөөртэй мэндчилгээг хүргэнэ.",
    "visitTitle": "Сүюүд уулзацгаая.\nНэг сайхан хоолны төлөө.",
    "address": "Сөүл, Ганбүк-гү, Упэсан-ру 397, 1-р давхар",
    "hoursTitle": "Ажиллах цаг",
    "weekdays": "Даваа, Лхагва, Пүрэв, Баасан 11:00–14:00 / 16:00–22:00",
    "weekends": "Бямба, Ням, баярын өдөр 16:00–22:00",
    "closed": "Мягмар гарагт амарна",
    "hoursNote": "Ирэхээсээ өмнө ажиллах цагийг шалгаарай. Газрын нөхцөлөөс шалтгаалан цаг өөрчлөгдөж болно.",
    "directions": "Газрын зурагт зам харах",
    "call": "Хоолны газар руу залгах",
    "review": "Зочдын сэтгэгдэл унших · Google Maps",
    "prepayTitle": "Дахин ирдэг зочдод,\nөдөр тутмын хоолонд.",
    "prepayText": "Байнга ирдэг зочдод урьдчилан төлөх үйлчилгээ бий. Хүсэлт өгсний дараа газар төлбөрийг баталгаажуулж байж оноо нэмнэ. Маягт илгээх нь төлбөр төлөгдсөн эсвэл оноо нэмэгдсэн гэсэн үг биш.",
    "prepayCta": "Урьдчилан төлөх маягт · солонгос",
    "footer": "Ээжийн гарын амтаас эхэлж, ээж охин хоёрын өдөр тутамд үргэлжилнэ. Энэ бол Gayoungene.",
    "language": "Хэл сонгох",
    "nav": "Цэс нээх",
    "skip": "Агуулга руу очих",
    "close": "Хаах",
    "home": "Албан ёсны нүүр",
    "heroEyebrow": "СҮЮҮ, СӨҮЛИЙН СОЛОНГОС ХООЛ · GAYOUNGENE",
    "storyEyebrow": "01 / ЭЭЖ, ОХИНЫ ТҮҮХ",
    "handEyebrow": "ХАМТДАА АЖИЛЛАХ ӨДӨР БҮР",
    "logoEyebrow": "НЭР БА ДҮР",
    "learningEyebrow": "ҮРГЭЛЖ СУРАЛЦАНА",
    "foodEyebrow": "02 / МАНАЙ МЕНЮ",
    "welcomeEyebrow": "03 / ӨӨРИЙН ХЭЛЭЭР СОНГООРОЙ",
    "charactersEyebrow": "БЯЦХАН НАЙЗУУДТАЙ ТАНИЛЦААРАЙ",
    "eventEyebrow": "ГАЗРЫН МЭДЭЭ",
    "visitEyebrow": "04 / МАНАЙХААР ЗОЧЛООРОЙ",
    "openingLabel": "2022 ОНД СҮЮҮД ЭХЭЛСЭН ТҮҮХ",
    "handCaption": "Өдөр бүрийн хоолыг хамтдаа.",
    "logoCaption": "Гаёны зурсан ээжийн дүр.",
    "pauseMotion": "Гүйдэг бичгийг зогсоох",
    "playMotion": "Гүйдэг бичгийг үргэлжлүүлэх",
    "ribbonA": "Ээжийн гарын амт",
    "ribbonB": "Охиных нь оролцоо",
    "ribbonC": "Хамтдаа бэлтгэх зоог",
    "metaDescription": "Ээж 2012 оноос солонгос хөнгөн хоол хийж ирсэн. Охин Гаён нь газрынхаа нэр, логог бүтээсэн. Сөүлийн Сүюүд бид хамтдаа хоол хийж, таныг угтдаг."
  },
  "th": {
    "story": "เรื่องราวของเรา",
    "food": "เมนูอาหาร",
    "find": "เลือกเมนูที่ใช่",
    "prepay": "สมัครชำระล่วงหน้า",
    "visit": "แวะมาหาเรา",
    "heroA": "รสมือแม่",
    "heroB": "มื้อที่แม่ลูกทำด้วยกัน",
    "heroText": "แม่ทำอาหารเกาหลีมาตั้งแต่ปี 2012\nกายอง ลูกสาวผู้สร้างชื่อและใบหน้าให้ร้าน\nเราทำอาหารและต้อนรับคุณด้วยกันที่ซูยู กรุงโซล",
    "storyCta": "อ่านเรื่องราวของแม่ลูก",
    "menuCta": "ดูเมนูและราคา",
    "storyTitle": "จากความฝันของแม่\nสู่ร้านที่เปิดด้วยกัน",
    "storyLead": "แม่เริ่มทำงานเป็นพนักงานร้านอาหารเกาหลีในย่านยักซูดงเมื่อปี 2012 และสั่งสมฝีมือมาราวสิบปี เมื่อแม่ตั้งใจจะเปิดร้านของตัวเอง กายองก็มาช่วยกันเตรียมชื่อ โลโก้ และพื้นที่ร้านด้วยมือของทั้งคู่ วันที่ 12 กุมภาพันธ์ 2022 กายองอีเนจึงเปิดประตูต้อนรับในย่านซูยู",
    "year1": "แม่เริ่มสั่งสมประสบการณ์ทำอาหารในฐานะพนักงานร้านในยักซูดง",
    "year2": "แม่และลูกสาวเปิดกายองอีเนที่ซูยู วันที่ 12 กุมภาพันธ์",
    "year3": "ขยายไปยังพื้นที่ข้างกันในฤดูร้อน เพื่อให้ลูกค้านั่งทานได้สบายขึ้น",
    "handTitle": "ตั้งแต่เตรียมไส้คิมบับ\nจนถึงต้อนรับคุณ",
    "handText": "เราเตรียมไส้คิมบับและวัตถุดิบของทอดด้วยตัวเอง แม่รับหน้าที่ทำซอสหลัก ส่วนกายองร่วมทำอาหาร รับออเดอร์ ดูแลลูกค้า และเก็บร้าน เบื้องหลังอาหารเกาหลีจานคุ้นเคย คือการลงมือทำด้วยกันของแม่ลูก นี่คือทุกวันที่กายองอีเน",
    "logoTitle": "ชื่อของลูกสาว\nใบหน้าของแม่",
    "logoText": "ระหว่างเตรียมเปิดร้าน กายองวาดโลโก้ด้วยมือจากภาพถ่ายของแม่ ร้านจึงใช้ชื่อลูกสาวและต้อนรับคุณด้วยใบหน้าของแม่ เรื่องราวของร้านที่ทั้งคู่สร้างด้วยกันอยู่ในชื่อและโลโก้นี้",
    "portraitCaption": "กายองและแม่ ผู้ร่วมกันสร้างกายองอีเน",
    "openingCaption": "กายองอีเนเมื่อเปิดร้านในปี 2022 ราคาเมนูในภาพเป็นราคาของช่วงเวลานั้น",
    "foodTitle": "วันนี้\nอยากทานเมนูไหนดี?",
    "foodText": "ต็อกบกกีรสหวานเผ็ด คิมบับไส้แน่น หรือของทอดกรอบ แตะภาพเพื่อดูราคาและรายละเอียดของแต่ละเมนู",
    "dish1": "ต็อกบกกีดั้งเดิม 1988",
    "dish2": "คิมบับกายอง",
    "dish3": "ปลาหมึกทอดที่เตรียมด้วยมือ",
    "dishText1": "ต็อกและออมุกคลุกซอสหวานเผ็ด อาหารเกาหลีจานคุ้นเคยที่ชวนคิดถึง",
    "dishText2": "ข้าวน้อยลง ไข่และผักเต็มคำ ม้วนไส้แน่นสำหรับมื้อของคุณ",
    "dishText3": "ปลาหมึกหนึบนุ่มในแป้งกรอบ ทานคู่ต็อกบกกีหรือทานเดี่ยวก็ได้",
    "welcomeTitle": "เพิ่งลองอาหารเกาหลีครั้งแรก?\nเลือกได้อย่างสบายใจ",
    "welcomeText": "ดูภาพ วัตถุดิบ และระดับความเผ็ดในภาษาของคุณ เมื่อเลือกแล้ว สามารถแสดงชื่อเมนูภาษาเกาหลีให้พนักงานดูได้ เราเตรียมคำแนะนำไว้เพื่อให้เลือกมื้อวันนี้ได้ง่ายขึ้น",
    "charactersTitle": "เพื่อนตัวน้อยสองคนกับคำทักทายแสนอบอุ่น",
    "charactersText": "พบกับมัลลัง กายองและเพื่อนกระต่ายในผ้ากันเปื้อนสีส้ม ทั้งคู่ส่งคำทักทายสดใสจากกายองอีเนถึงคุณ",
    "visitTitle": "พบกันที่ซูยู\nพร้อมอาหารสักมื้อ",
    "address": "ชั้น 1 เลขที่ 397 ถนน Opaesan-ro เขต Gangbuk-gu โซล",
    "hoursTitle": "เวลาเปิดร้าน",
    "weekdays": "จันทร์ พุธ พฤหัสบดี ศุกร์ 11:00–14:00 / 16:00–22:00",
    "weekends": "เสาร์ อาทิตย์ และวันหยุด 16:00–22:00",
    "closed": "หยุดทุกวันอังคาร",
    "hoursNote": "โปรดตรวจสอบเวลาเปิดร้านก่อนมา เวลาอาจเปลี่ยนแปลงตามสถานการณ์ของร้าน",
    "directions": "ดูเส้นทางบนแผนที่",
    "call": "โทรหาร้าน",
    "review": "อ่านรีวิวจากผู้มาเยือน · Google Maps",
    "prepayTitle": "สำหรับคนคุ้นเคย\nและมื้อในทุกวัน",
    "prepayText": "ลูกค้าที่แวะมาบ่อยสามารถใช้บริการชำระล่วงหน้าได้ หลังส่งแบบฟอร์ม ร้านจะตรวจสอบการชำระเงินก่อนเติมแต้ม การส่งแบบฟอร์มเพียงอย่างเดียวยังไม่ใช่การชำระเงินหรือเติมแต้มสำเร็จ",
    "prepayCta": "เปิดแบบฟอร์มชำระล่วงหน้า · เกาหลี",
    "footer": "เริ่มจากรสมือแม่ สานต่อในทุกวันที่แม่ลูกทำด้วยกัน นี่คือกายองอีเน",
    "language": "เลือกภาษา",
    "nav": "เปิดเมนู",
    "skip": "ข้ามไปยังเนื้อหา",
    "close": "ปิด",
    "home": "หน้าหลักทางการ",
    "heroEyebrow": "อาหารเกาหลีในซูยู โซล · GAYOUNGENE",
    "storyEyebrow": "01 / เรื่องราวแม่ลูก",
    "handEyebrow": "ลงมือทำด้วยกันทุกวัน",
    "logoEyebrow": "ชื่อและใบหน้าของร้าน",
    "learningEyebrow": "ร้านที่เรียนรู้อยู่เสมอ",
    "foodEyebrow": "02 / เมนูกายองอีเน",
    "welcomeEyebrow": "03 / เลือกในภาษาของคุณ",
    "charactersEyebrow": "รู้จักเพื่อนตัวน้อยของเรา",
    "eventEyebrow": "ข่าวจากร้าน",
    "visitEyebrow": "04 / แวะมาพบกัน",
    "openingLabel": "เริ่มต้นที่ซูยู ปี 2022",
    "handCaption": "มื้อวันนี้ที่เตรียมด้วยกัน",
    "logoCaption": "ภาพแม่ที่กายองวาด",
    "pauseMotion": "หยุดข้อความเลื่อน",
    "playMotion": "เล่นข้อความเลื่อนต่อ",
    "ribbonA": "รสมือแม่",
    "ribbonB": "ฝีมือลูกสาว",
    "ribbonC": "มื้อที่ทำด้วยกัน",
    "metaDescription": "แม่ทำอาหารเกาหลีมาตั้งแต่ปี 2012 กายอง ลูกสาวผู้สร้างชื่อและใบหน้าให้ร้าน เราทำอาหารและต้อนรับคุณด้วยกันที่ซูยู กรุงโซล"
  },
  "ru": {
    "story": "Наша история",
    "food": "Наши блюда",
    "find": "Подобрать блюдо",
    "prepay": "Предоплата",
    "visit": "Как добраться",
    "heroA": "Мамины рецепты.",
    "heroB": "Готовим вместе.",
    "heroText": "Мама готовит корейские блюда с 2012 года.\nДочь Гаён придумала для кафе имя и нарисовала его лицо.\nВ Сую, Сеул, мы вместе готовим и встречаем вас.",
    "storyCta": "История мамы и дочери",
    "menuCta": "Посмотреть меню и цены",
    "storyTitle": "Мамина мечта.\nКафе, которое открыли вместе.",
    "storyLead": "В 2012 году мама начала работать сотрудницей кафе корейских закусок в Яксу-доне и около десяти лет оттачивала своё мастерство. Когда она решила открыть собственное дело, к ней присоединилась Гаён. Название, логотип и пространство они подготовили сами. 12 февраля 2022 года в Сую открылось Gayoungene.",
    "year1": "Мама начала набираться опыта, работая в кафе корейских закусок в Яксу-доне.",
    "year2": "12 февраля мама и дочь открыли Gayoungene в Сую.",
    "year3": "Летом расширили кафе в соседнее помещение, чтобы гостям было удобнее обедать.",
    "handTitle": "От начинки для кимпаба\nдо встречи с вами.",
    "handText": "Мы сами подготавливаем начинку для кимпаба и ингредиенты для жареных блюд. Мама делает основные соусы; Гаён тоже готовит, принимает заказы, встречает гостей и наводит порядок. За привычной тарелкой корейской еды стоит совместный труд двух людей. Так проходит каждый день в Gayoungene.",
    "logoTitle": "Имя дочери.\nЛицо мамы.",
    "logoText": "Готовясь к открытию, Гаён нарисовала логотип от руки по фотографии мамы. Кафе носит имя дочери и встречает гостей маминым лицом. В названии и рисунке — история места, которое они создали вместе.",
    "portraitCaption": "Гаён и её мама, которые вместе создают Gayoungene",
    "openingCaption": "Gayoungene при открытии в 2022 году. Цены в меню на фотографии относятся к тому времени.",
    "foodTitle": "Чего бы вам\nхотелось сегодня?",
    "foodText": "Сладко-острые ттокпокки, кимпаб с щедрой начинкой или что-нибудь хрустящее. Нажмите на фото, чтобы увидеть цену и описание блюда.",
    "dish1": "Классические ттокпокки 1988",
    "dish2": "Кимбап Гаён",
    "dish3": "Кальмар в хрустящей панировке",
    "dishText1": "Тток и рыбные котлетки в сладко-остром соусе. Знакомая тарелка корейской еды.",
    "dishText2": "Меньше риса, больше яйца и овощей. Начинка, щедро завёрнутая в один ролл.",
    "dishText3": "Упругий кальмар с хрустящей корочкой. Попробуйте с ттокпокки или отдельно.",
    "welcomeTitle": "Впервые пробуете пунсик?\nВыбирайте спокойно.",
    "welcomeText": "Смотрите фотографии, состав и остроту на своём языке. Выбрав блюдо, покажите его корейское название сотруднику. Мы подготовили подсказки, чтобы выбрать обед было немного проще.",
    "charactersTitle": "Два маленьких друга с тёплым приветствием",
    "charactersText": "Познакомьтесь с Маллан Гаён и её другом-кроликом в оранжевых фартуках. Они передают радостное приветствие Gayoungene.",
    "visitTitle": "Встретимся в Сую.\nПриходите поесть.",
    "address": "1-й этаж, 397 Opaesan-ro, Gangbuk-gu, Сеул",
    "hoursTitle": "Часы работы",
    "weekdays": "Пн, Ср, Чт, Пт 11:00–14:00 / 16:00–22:00",
    "weekends": "Сб, Вс и праздники 16:00–22:00",
    "closed": "Вторник — выходной",
    "hoursNote": "Перед визитом уточните часы работы. Они могут меняться в зависимости от обстоятельств.",
    "directions": "Маршрут на карте",
    "call": "Позвонить в кафе",
    "review": "Читать отзывы гостей · Google Maps",
    "prepayTitle": "Для знакомых лиц\nи повседневных обедов.",
    "prepayText": "Для постоянных гостей доступна предоплата. После заявки кафе подтверждает оплату и затем начисляет баллы. Отправка формы сама по себе не означает оплату или пополнение баллов.",
    "prepayCta": "Открыть заявку · на корейском",
    "footer": "От маминых рецептов к каждому дню, который мама и дочь проводят вместе. Это Gayoungene.",
    "language": "Выбрать язык",
    "nav": "Открыть навигацию",
    "skip": "Перейти к содержимому",
    "close": "Закрыть",
    "home": "Официальная главная",
    "heroEyebrow": "КОРЕЙСКАЯ КУХНЯ · СУЮ, СЕУЛ",
    "storyEyebrow": "01 / МАМА И ДОЧЬ",
    "handEyebrow": "ВМЕСТЕ КАЖДЫЙ ДЕНЬ",
    "logoEyebrow": "ИМЯ И ЛИЦО КАФЕ",
    "learningEyebrow": "ПРОДОЛЖАЕМ УЧИТЬСЯ",
    "foodEyebrow": "02 / МЕНЮ GAYOUNGENE",
    "welcomeEyebrow": "03 / НА ВАШЕМ ЯЗЫКЕ",
    "charactersEyebrow": "НАШИ МАЛЕНЬКИЕ ДРУЗЬЯ",
    "eventEyebrow": "НОВОСТИ КАФЕ",
    "visitEyebrow": "04 / ПРИХОДИТЕ К НАМ",
    "openingLabel": "НАЧАЛО В СУЮ, 2022",
    "handCaption": "Каждый день готовим вместе.",
    "logoCaption": "Мама глазами Гаён.",
    "pauseMotion": "Остановить бегущую строку",
    "playMotion": "Продолжить бегущую строку",
    "ribbonA": "Мамины рецепты",
    "ribbonB": "Руки дочери",
    "ribbonC": "Готовим вместе",
    "metaDescription": "Мама готовит корейские блюда с 2012 года. Дочь Гаён придумала для кафе имя и нарисовала его лицо. В Сую, Сеул, мы вместе готовим и встречаем вас."
  },
  "id": {
    "story": "Cerita kami",
    "food": "Menu kami",
    "find": "Temukan menu",
    "prepay": "Prapembayaran",
    "visit": "Kunjungi kami",
    "heroA": "Masakan Ibu,",
    "heroB": "dibuat bersama putrinya.",
    "heroText": "Ibu memasak hidangan Korea sejak 2012.\nPutrinya, Gayoung, memberi kedai ini nama dan wajah.\nDi Suyu, Seoul, kami memasak dan menyambut Anda bersama.",
    "storyCta": "Kenali ibu dan putri",
    "menuCta": "Lihat menu & harga",
    "storyTitle": "Dari impian Ibu,\nmenjadi kedai mereka bersama.",
    "storyLead": "Pada 2012, Ibu mulai bekerja sebagai karyawan kedai bunsik di Yaksu-dong dan mengasah keterampilan memasaknya selama sekitar sepuluh tahun. Saat Ibu ingin membuka kedai sendiri, Gayoung ikut membantu. Nama, logo, hingga ruang kedai mereka siapkan sendiri. Gayoungene dibuka di Suyu pada 12 Februari 2022.",
    "year1": "Ibu mulai bekerja dan belajar memasak di kedai bunsik di Yaksu-dong.",
    "year2": "Ibu dan putrinya membuka Gayoungene di Suyu pada 12 Februari.",
    "year3": "Memperluas kedai ke ruang sebelah pada musim panas agar tamu lebih nyaman makan.",
    "handTitle": "Dari menyiapkan isian,\nhingga menyambut Anda.",
    "handText": "Kami menyiapkan isian gimbap dan bahan gorengan dengan tangan sendiri. Ibu membuat saus utama; Gayoung ikut memasak, menerima pesanan, melayani, dan membereskan kedai. Dua orang bekerja bersama di balik sepiring hidangan Korea yang akrab. Inilah keseharian Gayoungene.",
    "logoTitle": "Nama sang putri.\nWajah sang ibu.",
    "logoText": "Saat menyiapkan kedai, Gayoung menggambar logo dengan tangan berdasarkan foto ibunya. Kedai ini memakai nama sang putri dan menyambut Anda dengan wajah sang ibu. Keduanya menjadi bagian dari tempat yang mereka bangun bersama.",
    "portraitCaption": "Gayoung dan ibunya, dua orang di balik Gayoungene",
    "openingCaption": "Gayoungene saat dibuka pada 2022. Harga menu pada foto adalah harga saat itu.",
    "foodTitle": "Hari ini,\ningin makan apa?",
    "foodText": "Tteokbokki manis pedas, gimbap berisi padat, atau gorengan renyah. Ketuk foto untuk melihat harga dan penjelasan hidangannya.",
    "dish1": "Tteokbokki Klasik 1988",
    "dish2": "Gimbap Gayoung",
    "dish3": "Cumi goreng yang disiapkan sendiri",
    "dishText1": "Tteok dan kue ikan dalam saus manis pedas. Sepiring rasa Korea yang akrab.",
    "dishText2": "Lebih sedikit nasi, lebih banyak telur dan sayuran. Isian melimpah dalam satu gulung.",
    "dishText3": "Cumi yang kenyal dengan lapisan renyah. Nikmati bersama tteokbokki atau tanpa pendamping.",
    "welcomeTitle": "Baru mencoba bunsik?\nPilih dengan nyaman.",
    "welcomeText": "Lihat foto, bahan, dan tingkat kepedasan dalam bahasa Anda. Setelah memilih, tunjukkan nama hidangan dalam bahasa Korea kepada staf. Sedikit bantuan agar memilih makanan terasa lebih mudah.",
    "charactersTitle": "Dua teman kecil, satu sambutan hangat",
    "charactersText": "Temui Mallang Gayoung dan sahabat kelincinya dengan celemek oranye. Mereka membawa sapaan ceria dari Gayoungene.",
    "visitTitle": "Temui kami di Suyu.\nMari menikmati satu hidangan.",
    "address": "Lantai 1, 397 Opaesan-ro, Gangbuk-gu, Seoul",
    "hoursTitle": "Jam buka",
    "weekdays": "Sen, Rab, Kam, Jum 11:00–14:00 / 16:00–22:00",
    "weekends": "Sab, Min & hari libur 16:00–22:00",
    "closed": "Tutup hari Selasa",
    "hoursNote": "Periksa jam buka sebelum berkunjung. Jam dapat berubah mengikuti kondisi kedai.",
    "directions": "Lihat petunjuk arah",
    "call": "Telepon kedai",
    "review": "Baca ulasan pengunjung · Google Maps",
    "prepayTitle": "Untuk wajah yang akrab\ndan santapan sehari-hari.",
    "prepayText": "Layanan prapembayaran tersedia bagi tamu yang sering datang. Setelah formulir dikirim, kedai mengonfirmasi pembayaran sebelum menambahkan poin. Mengirim formulir belum menyelesaikan pembayaran atau menambah poin.",
    "prepayCta": "Buka formulir prabayar · Korea",
    "footer": "Berawal dari masakan Ibu, berlanjut dalam keseharian ibu dan putrinya. Inilah Gayoungene.",
    "language": "Pilih bahasa",
    "nav": "Buka navigasi",
    "skip": "Lewati ke isi",
    "close": "Tutup",
    "home": "Beranda resmi",
    "heroEyebrow": "HIDANGAN KOREA DI SUYU, SEOUL · GAYOUNGENE",
    "storyEyebrow": "01 / IBU DAN PUTRINYA",
    "handEyebrow": "BEKERJA BERSAMA SETIAP HARI",
    "logoEyebrow": "NAMA DAN WAJAH KEDAI",
    "learningEyebrow": "TERUS BELAJAR",
    "foodEyebrow": "02 / MENU GAYOUNGENE",
    "welcomeEyebrow": "03 / PILIH DALAM BAHASA ANDA",
    "charactersEyebrow": "KENALI TEMAN KECIL KAMI",
    "eventEyebrow": "KABAR DARI KEDAI",
    "visitEyebrow": "04 / MARI BERKUNJUNG",
    "openingLabel": "BERAWAL DI SUYU, 2022",
    "handCaption": "Menyiapkan hidangan bersama.",
    "logoCaption": "Ibu, dalam gambar Gayoung.",
    "pauseMotion": "Jeda teks berjalan",
    "playMotion": "Lanjutkan teks berjalan",
    "ribbonA": "Masakan Ibu",
    "ribbonB": "Sentuhan putrinya",
    "ribbonC": "Dibuat bersama",
    "metaDescription": "Ibu memasak hidangan Korea sejak 2012. Putrinya, Gayoung, memberi kedai ini nama dan wajah. Di Suyu, Seoul, kami memasak dan menyambut Anda bersama."
  }
};
