export const experience={
  "ko": {
    "menu": "메뉴",
    "visit": "방문 안내",
    "friends": "두 친구",
    "guide": "이용 방법",
    "contact": "가게와 연결하기",
    "socialTitle": "가게의 오늘이 궁금하다면.",
    "socialText": "소식은 채널에서, 궁금한 점은 매장으로 편하게 연락해 주세요.",
    "newWindow": "새 창",
    "prepay": "선결제 서비스",
    "blog": "가영이 직접 쓴 이야기",
    "menuTitle": "오늘의 메뉴",
    "menuIntro": "메뉴와 가격을 먼저 살펴보세요. 고르기 어렵다면 추천을 받아보세요.",
    "ethosTitle": "작은 가게,\n우리다운 방식으로.",
    "recordTitle": "엄마의 ‘두 국자’를,\n가영의 기록으로.",
    "recordText": "오래 쌓인 엄마의 조리 감각을 듣고 기록합니다. 손님들의 반응을 살피며 메뉴와 안내를 고치고, 배민아카데미에서 배운 것도 가게에서 직접 해봅니다. 가영이네는 모녀가 함께 일하며 조금씩 바꿔가는 가게입니다.",
    "originTitle": "엄마의 꿈에서 시작해,\n모녀의 가게가 되기까지.",
    "originText": "2012년 약수동 분식집 직원으로 시작한 엄마. 약 10년 동안 쌓은 경험으로 자신의 가게를 준비했고, 딸 가영이 곁에서 함께했습니다. 공간을 직접 고치고 이름과 로고, 메뉴판까지 만들며 2022년 2월 12일 수유에 문을 열었습니다.",
    "signatureTitle": "길쭉해서 눈길,\n속이 알차서 한 입 더.",
    "signatureText": "떡볶이와 함께 떠올릴 가영이네의 한 가지. 23cm 왕김말이에 볶은 돼지고기와 오이고추, 당면을 담았습니다.",
    "foodLabel": "가영이네의 한 접시",
    "allMenu": "모두 보기",
    "navMenu": "메뉴",
    "more": "더 알아보기",
    "phone": "가게 전화",
    "recommend": "메뉴 고르기 도와드릴까요?"
  },
  "en": {
    "menu": "Menu",
    "visit": "Visit",
    "friends": "Our friends",
    "guide": "How to order",
    "contact": "Stay in touch",
    "socialTitle": "A little more Gayoungene.",
    "socialText": "Find our latest news or contact the shop with a question.",
    "newWindow": "New window",
    "prepay": "Prepay service",
    "blog": "Stories by Gayoung",
    "menuTitle": "On the menu",
    "menuIntro": "Browse dishes and prices. Need a hand choosing? Try our suggestions.",
    "ethosTitle": "A small shop.\nOur own way.",
    "recordTitle": "Mom’s ‘two ladles’,\nwritten down by Gayoung.",
    "recordText": "We listen to Mom’s cooking know-how and write it down. We refine dishes and guidance from guest feedback, and try what we learn at Baemin Academy in the shop. Gayoungene keeps changing, with mother and daughter working together.",
    "originTitle": "A mother’s dream.\nA shop made together.",
    "originText": "Mom began as an employee at a bunsik shop in Yaksu-dong in 2012. After about ten years, she prepared to open her own place, with Gayoung by her side. Together they worked on the space, name, logo and menu board, opening in Suyu on February 12, 2022.",
    "signatureTitle": "Long on crunch.\nFull of flavor.",
    "signatureText": "A Gayoungene signature to enjoy with tteokbokki: a 23 cm seaweed roll filled with stir-fried pork, cucumber chili pepper and glass noodles.",
    "foodLabel": "A taste of Gayoungene",
    "allMenu": "See all dishes",
    "navMenu": "Menu",
    "more": "More to know",
    "phone": "Call the shop",
    "recommend": "Need a hand choosing?"
  },
  "zh-Hans": {
    "menu": "菜单",
    "visit": "到店指南",
    "friends": "小伙伴",
    "guide": "用餐方式",
    "contact": "联系店铺",
    "socialTitle": "再多了解一点佳映家。",
    "socialText": "在官方渠道看看近况，有问题也欢迎联系店铺。",
    "newWindow": "新窗口",
    "prepay": "预付服务",
    "blog": "佳映写下的故事",
    "menuTitle": "今天吃什么",
    "menuIntro": "先看看菜品和价格。拿不定主意时，也可以试试推荐。",
    "ethosTitle": "小小的店，\n有自己的方式。",
    "recordTitle": "把妈妈的“两勺”，\n写进佳映的记录里。",
    "recordText": "我们听妈妈讲烹饪经验，把手感写下来。根据客人的反馈调整菜单和说明，也把在 Baemin Academy 学到的方法带回店里。母女一起工作，让佳映家一点点变得更好。",
    "originTitle": "从妈妈的梦想，\n到母女一起的店。",
    "originText": "2012年，妈妈从药水洞一家韩式小吃店的员工做起。积累约十年经验后，她准备开自己的店，女儿佳映也加入了。一起改造空间、设计店名、标志和菜单，2022年2月12日在水逾开门迎客。",
    "signatureTitle": "长长一卷，\n满满一口。",
    "signatureText": "搭配辣炒年糕的佳映家招牌：23厘米紫菜卷，包入炒猪肉、黄瓜辣椒和粉丝。",
    "foodLabel": "佳映家的一盘味道",
    "allMenu": "查看全部",
    "navMenu": "菜单",
    "more": "了解更多",
    "phone": "致电店铺",
    "recommend": "选菜需要帮忙吗？"
  },
  "ja": {
    "menu": "メニュー",
    "visit": "ご来店案内",
    "friends": "仲間たち",
    "guide": "ご利用方法",
    "contact": "お店とつながる",
    "socialTitle": "カヨンイネを、もう少し。",
    "socialText": "日々のお知らせは公式チャンネルへ。ご質問はお店までどうぞ。",
    "newWindow": "別ウィンドウ",
    "prepay": "前払いサービス",
    "blog": "カヨンが書いた物語",
    "menuTitle": "今日のメニュー",
    "menuIntro": "料理と価格を見てみましょう。迷ったら、おすすめもご案内します。",
    "ethosTitle": "小さなお店。\n私たちらしいやり方で。",
    "recordTitle": "お母さんの「お玉二杯」を、\nカヨンの記録に。",
    "recordText": "お母さんの調理の感覚を聞き、書き留めています。お客様の反応からメニューや案内を見直し、Baemin Academyで学んだこともお店で実践。母と娘が一緒に働きながら、少しずつ変わり続けています。",
    "originTitle": "お母さんの夢から、\n二人でつくるお店へ。",
    "originText": "2012年、薬水洞の粉食店の従業員として働き始めたお母さん。約10年の経験を重ね、自分のお店を開く準備に娘のカヨンも加わりました。空間を整え、店名・ロゴ・メニュー表をつくり、2022年2月12日に水踰で開店しました。",
    "signatureTitle": "長くて、サクッと。\n中身もしっかり。",
    "signatureText": "トッポッキのお供に、カヨンイネの看板メニューを。炒めた豚肉、キュウリ唐辛子、春雨を包んだ23cmのキムマリです。",
    "foodLabel": "カヨンイネのひと皿",
    "allMenu": "すべて見る",
    "navMenu": "メニュー",
    "more": "もっと知る",
    "phone": "お店に電話",
    "recommend": "メニュー選びをお手伝いしますか？"
  },
  "vi": {
    "menu": "Thực đơn",
    "visit": "Ghé quán",
    "friends": "Hai người bạn",
    "guide": "Cách dùng bữa",
    "contact": "Kết nối với quán",
    "socialTitle": "Thêm một chút Gayoungene.",
    "socialText": "Theo dõi tin mới trên các kênh hoặc liên hệ quán khi có thắc mắc.",
    "newWindow": "Cửa sổ mới",
    "prepay": "Dịch vụ trả trước",
    "blog": "Câu chuyện của Gayoung",
    "menuTitle": "Hôm nay ăn gì",
    "menuIntro": "Xem món và giá trước. Nếu khó chọn, hãy thử gợi ý của quán.",
    "ethosTitle": "Quán nhỏ.\nCách riêng của hai mẹ con.",
    "recordTitle": "‘Hai muôi’ của mẹ,\nđược Gayoung ghi lại.",
    "recordText": "Chúng tôi lắng nghe và ghi lại kinh nghiệm nấu ăn của mẹ. Hai mẹ con điều chỉnh món và hướng dẫn theo phản hồi của khách, rồi thử áp dụng những điều học ở Baemin Academy. Gayoungene thay đổi từng chút trong những ngày cùng làm việc.",
    "originTitle": "Từ ước mơ của mẹ,\nđến quán của hai mẹ con.",
    "originText": "Mẹ bắt đầu làm nhân viên ở một quán bunsik tại Yaksu-dong năm 2012. Sau khoảng mười năm, mẹ chuẩn bị mở quán riêng cùng Gayoung. Hai mẹ con sửa không gian, làm tên quán, logo và bảng thực đơn, rồi mở cửa tại Suyu ngày 12/2/2022.",
    "signatureTitle": "Dài giòn hấp dẫn,\nđầy đặn bên trong.",
    "signatureText": "Món đặc trưng dùng cùng tteokbokki: cuốn rong biển 23 cm với thịt heo xào, ớt dưa chuột và miến.",
    "foodLabel": "Một phần hương vị Gayoungene",
    "allMenu": "Xem tất cả món",
    "navMenu": "Thực đơn",
    "more": "Tìm hiểu thêm",
    "phone": "Gọi cho quán",
    "recommend": "Cần giúp chọn món?"
  },
  "mn": {
    "menu": "Цэс",
    "visit": "Зочлох",
    "friends": "Найзууд",
    "guide": "Үйлчлүүлэх заавар",
    "contact": "Холбогдох",
    "socialTitle": "Гаёнгенэг илүү таньцгаая.",
    "socialText": "Шинэ мэдээг сувгуудаас үзэж, асуух зүйлээ дэлгүүртэй холбоо барин лавлаарай.",
    "newWindow": "Шинэ цонх",
    "prepay": "Урьдчилсан төлбөр",
    "blog": "Гаёны бичсэн түүх",
    "menuTitle": "Өнөөдрийн цэс",
    "menuIntro": "Хоол, үнийг үзээрэй. Сонгоход хэцүү байвал санал болгох хоолыг хараарай.",
    "ethosTitle": "Жижигхэн газар.\nБидний өөрийн арга.",
    "recordTitle": "Ээжийн ‘хоёр шанага’-ыг\nГаён тэмдэглэж авна.",
    "recordText": "Ээжийн хоол хийх мэдрэмжийг сонсож тэмдэглэдэг. Зочдын саналд тулгуурлан цэс, заавраа шинэчилж, Baemin Academy-д сурсан зүйлээ ажилдаа туршдаг. Ээж, охин хоёр хамт ажиллан Гаёнгенэг бага багаар өөрчилж байна.",
    "originTitle": "Ээжийн мөрөөдлөөс,\nхамтын дэлгүүр хүртэл.",
    "originText": "Ээж 2012 онд Яксу-дон дахь бүншигийн газарт ажилтнаар эхэлсэн. Арав орчим жилийн туршлага хуримтлуулсны дараа өөрийн газраа нээхэд охин Гаён нь хамт байлаа. Тэд орчноо тохижуулж, нэр, лого, цэсээ бүтээн 2022 оны 2-р сарын 12-нд Сүюд үүдээ нээсэн.",
    "signatureTitle": "Урт, шаржигнуур.\nДотроо дүүрэн.",
    "signatureText": "Ттокпоккитой хамт идэх Гаёнгенэгийн онцлох хоол: хуурсан гахайн мах, өргөст хэмх хэлбэрийн чинжүү, шилэн гоймонтой 23 см далайн байцааны ороомог.",
    "foodLabel": "Гаёнгенэгийн нэг таваг",
    "allMenu": "Бүх хоол",
    "navMenu": "Цэс",
    "more": "Дэлгэрэнгүй",
    "phone": "Залгах",
    "recommend": "Хоол сонгоход туслах уу?"
  },
  "th": {
    "menu": "เมนู",
    "visit": "มาเยือนร้าน",
    "friends": "เพื่อนของเรา",
    "guide": "วิธีใช้บริการ",
    "contact": "ติดต่อร้าน",
    "socialTitle": "รู้จักกายองเนอีกนิด",
    "socialText": "ติดตามข่าวสารผ่านช่องทางของร้าน หรือติดต่อเราเมื่อมีคำถาม",
    "newWindow": "หน้าต่างใหม่",
    "prepay": "บริการชำระล่วงหน้า",
    "blog": "เรื่องเล่าจากกายอง",
    "menuTitle": "วันนี้กินอะไรดี",
    "menuIntro": "ดูเมนูและราคาก่อน หากเลือกไม่ถูก ลองดูเมนูแนะนำได้",
    "ethosTitle": "ร้านเล็ก ๆ\nในแบบของเรา",
    "recordTitle": "‘สองกระบวย’ ของแม่\nสู่บันทึกของกายอง",
    "recordText": "เราฟังและจดบันทึกประสบการณ์ทำอาหารของแม่ ปรับเมนูและคำแนะนำตามเสียงของลูกค้า และนำสิ่งที่เรียนจาก Baemin Academy มาลองในร้าน กายองเนค่อย ๆ เปลี่ยนไปผ่านการทำงานร่วมกันของแม่และลูกสาว",
    "originTitle": "จากความฝันของแม่\nสู่ร้านของเราสองคน",
    "originText": "แม่เริ่มเป็นพนักงานร้านบุนชิกที่ยักซูดงในปี 2012 หลังสะสมประสบการณ์ราวสิบปี แม่เตรียมเปิดร้านของตัวเองโดยมีกายองอยู่ข้าง ๆ ทั้งคู่ปรับปรุงพื้นที่ ออกแบบชื่อ โลโก้ และป้ายเมนู ก่อนเปิดร้านที่ซูยูเมื่อ 12 กุมภาพันธ์ 2022",
    "signatureTitle": "ยาวกรอบสะดุดตา\nไส้เต็มคำ",
    "signatureText": "เมนูเด่นของกายองเนที่กินคู่กับต็อกบกกี: สาหร่ายม้วน 23 ซม. ใส่หมูผัด พริกแตงกวา และวุ้นเส้น",
    "foodLabel": "กายองเนในหนึ่งจาน",
    "allMenu": "ดูเมนูทั้งหมด",
    "navMenu": "เมนู",
    "more": "รู้จักเพิ่มเติม",
    "phone": "โทรหาร้าน",
    "recommend": "ให้เราช่วยเลือกเมนูไหม?"
  },
  "ru": {
    "menu": "Меню",
    "visit": "Как нас найти",
    "friends": "Наши друзья",
    "guide": "Как заказать",
    "contact": "Связаться",
    "socialTitle": "Ещё немного о Gayoungene.",
    "socialText": "Следите за новостями в наших каналах или задайте вопрос по телефону.",
    "newWindow": "Новое окно",
    "prepay": "Предоплата",
    "blog": "Истории Каён",
    "menuTitle": "Что в меню",
    "menuIntro": "Посмотрите блюда и цены. Трудно выбрать? Воспользуйтесь подсказками.",
    "ethosTitle": "Маленькое кафе.\nНаш собственный путь.",
    "recordTitle": "Мамины «два половника»\nв записях Каён.",
    "recordText": "Мы слушаем мамины кулинарные советы и записываем их. По отзывам гостей меняем меню и подсказки, пробуем на практике то, чему учимся в Baemin Academy. Мама и дочь работают вместе, и кафе постепенно меняется.",
    "originTitle": "От маминой мечты\nк общему делу.",
    "originText": "В 2012 году мама начала работать в кафе пунсик в Яксу-доне. Примерно через десять лет она стала готовиться к открытию своего заведения вместе с дочерью Каён. Они сами обустроили пространство, придумали название, логотип и меню. Кафе открылось в Сую 12 февраля 2022 года.",
    "signatureTitle": "Длинный и хрустящий.\nС начинкой внутри.",
    "signatureText": "Фирменное дополнение к ттокпокки: рулет из водорослей длиной 23 см с обжаренной свининой, огуречным перцем и стеклянной лапшой.",
    "foodLabel": "Вкус Gayoungene",
    "allMenu": "Все блюда",
    "navMenu": "Меню",
    "more": "Узнать больше",
    "phone": "Позвонить",
    "recommend": "Помочь с выбором?"
  },
  "id": {
    "menu": "Menu",
    "visit": "Berkunjung",
    "friends": "Dua sahabat",
    "guide": "Cara menikmati",
    "contact": "Hubungi kami",
    "socialTitle": "Lebih dekat dengan Gayoungene.",
    "socialText": "Ikuti kabar terbaru di kanal kami atau hubungi kedai jika ada pertanyaan.",
    "newWindow": "Jendela baru",
    "prepay": "Layanan prabayar",
    "blog": "Cerita dari Gayoung",
    "menuTitle": "Mau makan apa",
    "menuIntro": "Lihat hidangan dan harga. Jika sulit memilih, coba rekomendasi kami.",
    "ethosTitle": "Kedai kecil.\nDengan cara kami.",
    "recordTitle": "‘Dua sendok sayur’ Ibu,\ndicatat oleh Gayoung.",
    "recordText": "Kami mendengar dan mencatat pengalaman memasak Ibu. Tanggapan tamu membantu kami memperbaiki menu dan panduan, serta mencoba hal yang dipelajari di Baemin Academy. Ibu dan putri bekerja bersama, membawa perubahan kecil ke Gayoungene.",
    "originTitle": "Dari mimpi Ibu,\nmenjadi kedai bersama.",
    "originText": "Ibu mulai sebagai pegawai kedai bunsik di Yaksu-dong pada 2012. Setelah sekitar sepuluh tahun, ia bersiap membuka kedai sendiri bersama Gayoung. Mereka menata ruang, membuat nama, logo dan papan menu, lalu membuka pintu di Suyu pada 12 Februari 2022.",
    "signatureTitle": "Panjang dan renyah.\nPenuh isi.",
    "signatureText": "Menu khas Gayoungene untuk menemani tteokbokki: gulungan rumput laut 23 cm berisi babi tumis, cabai mentimun dan soun.",
    "foodLabel": "Sepiring Gayoungene",
    "allMenu": "Lihat semua",
    "navMenu": "Menu",
    "more": "Kenali lebih jauh",
    "phone": "Telepon kedai",
    "recommend": "Perlu bantuan memilih?"
  },
  "fr": {
    "menu": "Menu",
    "visit": "Nous trouver",
    "friends": "Nos amis",
    "guide": "Comment commander",
    "contact": "Nous contacter",
    "socialTitle": "Un peu plus de Gayoungene.",
    "socialText": "Suivez nos actualités ou appelez le restaurant pour toute question.",
    "newWindow": "Nouvelle fenêtre",
    "prepay": "Prépaiement",
    "blog": "Les histoires de Gayoung",
    "menuTitle": "À la carte",
    "menuIntro": "Découvrez les plats et les prix. Besoin d’aide pour choisir ? Essayez nos suggestions.",
    "ethosTitle": "Un petit restaurant.\nNotre façon de faire.",
    "recordTitle": "Les ‘deux louches’ de maman,\nnotées par Gayoung.",
    "recordText": "Nous écoutons et notons le savoir-faire de maman. Les retours des clients nous aident à améliorer le menu et nos explications, et nous appliquons ce que nous apprenons à Baemin Academy.",
    "originTitle": "Du rêve d’une mère\nà un restaurant à deux.",
    "originText": "Maman a commencé comme employée dans un restaurant de bunsik à Yaksu-dong en 2012. Après environ dix ans, elle a préparé l’ouverture de son propre lieu avec Gayoung. Elles ont aménagé l’espace, créé le nom, le logo et le menu, puis ouvert à Suyu le 12 février 2022.",
    "signatureTitle": "Long et croustillant.\nBien garni.",
    "signatureText": "Une spécialité de Gayoungene à accompagner de tteokbokki : un rouleau d’algue de 23 cm au porc sauté, piment concombre et vermicelles.",
    "foodLabel": "Une assiette de Gayoungene",
    "allMenu": "Tous les plats",
    "navMenu": "Menu",
    "more": "En savoir plus",
    "phone": "Appeler",
    "recommend": "Besoin d’aide pour choisir ?"
  }
};
