export const extras={
  "ko": {
    "blog": "가영이 직접 쓴 이야기 더 읽기",
    "learningTitle": "오래 해온 손맛에,\n새로 배운 것을 더합니다.",
    "learningText": "엄마의 감각을 기록하고, 손님들의 반응을 살피며 메뉴와 운영을 다듬습니다. 배움이 수료증으로 끝나지 않고 가게의 하루로 이어지도록, 모녀는 지금도 공부합니다.",
    "certAlt": "매장에 전시된 배민아카데미 수료증과 배민프렌즈 위촉장",
    "certCaption": "배민아카데미 교육과 배민프렌즈 활동의 기록입니다. 음식 품질 인증을 뜻하지 않습니다.",
    "educationTitle": "배운 것을 가게의 하루로",
    "educationText": "배민아카데미에서 글쓰기와 가게 운영을 배우고, 손님과 소통하는 방법을 고민합니다. 가영의 배민프렌즈 활동도 더 나은 가게를 위한 배움의 과정입니다.",
    "trademarkTitle": "직접 만들고, 직접 등록한 이름",
    "trademarkText": "이름과 로고를 기획한 가영은 가영이네 상표등록도 직접 진행해 마쳤습니다. 우리 가게만의 얼굴과 이야기를 꾸준히 가꾸어갑니다.",
    "sinceNote": "포스터의 SINCE 2012는 엄마가 분식 일을 시작한 해입니다. 가영이네의 개업은 2022년입니다.",
    "eventTitle": "한 끼의 이야기를,\n들려주세요.",
    "eventText": "네이버 영수증 리뷰 이벤트를 매장에서 안내하고 있습니다. 참여 방법과 쿨피스 제공 혜택은 방문하실 때 직원에게 확인해 주세요.",
    "eventNote": "다른 이벤트와 중복 참여할 수 없습니다. 진행 여부와 혜택은 매장에 확인해 주세요."
  },
  "en": {
    "blog": "Read more from Gayoung",
    "learningTitle": "Experience in the kitchen.\nAlways room to learn.",
    "learningText": "We write down Mom’s cooking knowledge, listen to guests and refine our menu and daily work. Learning belongs in the life of the shop, beyond the certificates on the wall.",
    "certAlt": "Baemin Academy completion certificates and a Baemin Friends appointment displayed in the shop",
    "certCaption": "Records of Baemin Academy training and Baemin Friends activities. These are not food-quality certifications.",
    "educationTitle": "Bringing what we learn into the shop",
    "educationText": "Through Baemin Academy, we study writing and shop operations, including how to communicate with guests. Gayoung’s Baemin Friends activities are part of that ongoing learning.",
    "trademarkTitle": "A name we created and registered",
    "trademarkText": "Gayoung planned the name and logo, then completed the trademark registration herself. We continue to care for the identity and story of our shop.",
    "sinceNote": "SINCE 2012 on the poster marks the start of Mom’s bunsik career. Gayoungene opened in 2022.",
    "eventTitle": "Tell us about\nyour meal.",
    "eventText": "Ask staff about the Naver receipt-review event and its Coolpis drink offer when you visit.",
    "eventNote": "Cannot be combined with other events. Please confirm availability and benefits with the shop."
  },
  "zh-Hans": {
    "blog": "继续阅读佳映写下的故事",
    "learningTitle": "积累下来的手艺，\n也不断加入新的学习。",
    "learningText": "记录妈妈的烹饪经验，听取客人的反馈，改进菜单与日常经营。学习不止于墙上的证书，更要走进店铺的每一天。",
    "certAlt": "店内展示的Baemin Academy结业证书及Baemin Friends委任状",
    "certCaption": "Baemin Academy培训及Baemin Friends活动的记录，并非食品质量认证。",
    "educationTitle": "把学到的带回店里",
    "educationText": "通过Baemin Academy学习写作和店铺经营，也思考如何与客人沟通。佳映的Baemin Friends活动，同样是持续学习的一部分。",
    "trademarkTitle": "亲手设计，也亲自注册的名字",
    "trademarkText": "规划了店名与标志的佳映，也亲自完成了佳映家的商标注册。我们继续用心经营这家店独有的形象与故事。",
    "sinceNote": "海报上的SINCE 2012指妈妈开始从事韩式小吃工作的年份。佳映家于2022年开业。",
    "eventTitle": "说说您\n这一餐的感受。",
    "eventText": "到店时，可以向店员了解Naver收据评价活动的参与方式及Coolpis饮品福利。",
    "eventNote": "不可与其他活动同时参与。是否正在举行及具体福利，请向店铺确认。"
  },
  "ja": {
    "blog": "カヨンが書く物語をもっと読む",
    "learningTitle": "積み重ねた味に、\n新しい学びを。",
    "learningText": "母の料理の感覚を記録し、お客様の声に耳を傾け、メニューや日々の仕事を見直す。学びを壁の修了証だけで終わらせず、お店の毎日へつなげています。",
    "certAlt": "店内のBaemin Academy修了証とBaemin Friends委嘱状",
    "certCaption": "Baemin Academyでの受講とBaemin Friends活動の記録です。食品の品質認証ではありません。",
    "educationTitle": "学んだことを、お店の日常へ",
    "educationText": "Baemin Academyで文章や店舗運営を学び、お客様との伝え方を考えます。カヨンのBaemin Friends活動も、その学びの一部です。",
    "trademarkTitle": "自分で作り、自分で登録した名前",
    "trademarkText": "名前とロゴを企画したカヨンが、商標登録も自ら行いました。この店ならではの顔と物語を、これからも育てていきます。",
    "sinceNote": "ポスターのSINCE 2012は、母が韓国軽食の仕事を始めた年です。カヨンイネの開店は2022年です。",
    "eventTitle": "今日の一食の感想を、\n聞かせてください。",
    "eventText": "Naverのレシート口コミイベントとCoolpisドリンクの特典について、来店時にスタッフへお尋ねください。",
    "eventNote": "他のイベントとの併用はできません。実施状況と特典はお店でご確認ください。"
  },
  "vi": {
    "blog": "Đọc thêm chuyện do Gayoung viết",
    "learningTitle": "Tay nghề đã tích lũy,\nluôn thêm điều mới học.",
    "learningText": "Ghi lại kinh nghiệm nấu ăn của mẹ, lắng nghe khách và điều chỉnh thực đơn, công việc hằng ngày. Việc học không chỉ nằm trên chứng nhận mà còn đi vào cuộc sống của quán.",
    "certAlt": "Chứng nhận Baemin Academy và giấy bổ nhiệm Baemin Friends trong quán",
    "certCaption": "Ghi nhận khóa học Baemin Academy và hoạt động Baemin Friends, không phải chứng nhận chất lượng thực phẩm.",
    "educationTitle": "Mang điều học được vào quán",
    "educationText": "Qua Baemin Academy, chúng tôi học viết, vận hành quán và cách giao tiếp với khách. Hoạt động Baemin Friends của Gayoung cũng là một phần của quá trình học hỏi ấy.",
    "trademarkTitle": "Tự tạo nên và tự đăng ký tên quán",
    "trademarkText": "Gayoung thiết kế tên gọi, logo và tự hoàn tất đăng ký nhãn hiệu Gayoungene. Chúng tôi tiếp tục chăm chút bản sắc và câu chuyện riêng của quán.",
    "sinceNote": "SINCE 2012 trên áp phích chỉ năm mẹ bắt đầu làm món ăn Hàn. Gayoungene mở cửa năm 2022.",
    "eventTitle": "Kể chúng tôi nghe\nvề bữa ăn của bạn.",
    "eventText": "Khi ghé quán, hãy hỏi nhân viên về sự kiện đánh giá hóa đơn Naver và ưu đãi nước Coolpis.",
    "eventNote": "Không kết hợp với sự kiện khác. Vui lòng xác nhận chương trình và ưu đãi hiện có tại quán."
  },
  "mn": {
    "blog": "Гаёны бичсэн түүхийг дэлгэрүүлэн унших",
    "learningTitle": "Хуримтлуулсан туршлагадаа\nшинэ мэдлэг нэмдэг.",
    "learningText": "Ээжийн хоол хийх арга барилыг тэмдэглэж, зочдоо сонсож, меню болон ажлаа сайжруулдаг. Суралцах нь ханан дээрх гэрчилгээгээр дуусахгүй, газрын өдөр тутмын амьдралд үргэлжилнэ.",
    "certAlt": "Baemin Academy сургалтын гэрчилгээ болон Baemin Friends томилолт",
    "certCaption": "Baemin Academy сургалт болон Baemin Friends үйл ажиллагааны баримт. Хоолны чанарын баталгаажуулалт биш.",
    "educationTitle": "Сурснаа өдөр тутмын ажилдаа хэрэглэх",
    "educationText": "Baemin Academy-гаар дамжуулан бичих, газар ажиллуулах, зочидтой харилцах аргыг сурдаг. Гаёны Baemin Friends үйл ажиллагаа ч энэ тасралтгүй сургалтын нэг хэсэг.",
    "trademarkTitle": "Өөрсдөө бүтээж, бүртгүүлсэн нэр",
    "trademarkText": "Нэр, логог төлөвлөсөн Гаён Gayoungene-гийн барааны тэмдгийн бүртгэлийг өөрөө хийж дуусгасан. Бид газрынхаа төрх, түүхийг цаашид ч тордож явна.",
    "sinceNote": "Зурагт хуудасны SINCE 2012 нь ээжийн солонгос хөнгөн хоолны ажил эхэлсэн он. Gayoungene 2022 онд нээгдсэн.",
    "eventTitle": "Хоолныхоо тухай\nбидэнд хуваалцаарай.",
    "eventText": "Ирэхдээ Naver-ийн баримттай сэтгэгдлийн арга хэмжээ болон Coolpis ундааны урамшууллын талаар ажилтнаас асуугаарай.",
    "eventNote": "Бусад арга хэмжээтэй давхар оролцохгүй. Үргэлжилж буй эсэх болон урамшууллыг газраас лавлана уу."
  },
  "th": {
    "blog": "อ่านเรื่องที่กายองเขียนเพิ่มเติม",
    "learningTitle": "เติมสิ่งที่ได้เรียนรู้ใหม่\nให้รสมือที่สั่งสมมา",
    "learningText": "เราจดบันทึกประสบการณ์ทำอาหารของแม่ ฟังเสียงลูกค้า และปรับเมนูกับการทำงาน การเรียนรู้จึงไม่หยุดอยู่ที่ใบรับรองบนผนัง แต่เดินต่อในทุกวันของร้าน",
    "certAlt": "ใบประกาศจบหลักสูตร Baemin Academy และหนังสือแต่งตั้ง Baemin Friends ในร้าน",
    "certCaption": "บันทึกการอบรม Baemin Academy และกิจกรรม Baemin Friends ไม่ใช่ใบรับรองคุณภาพอาหาร",
    "educationTitle": "นำสิ่งที่เรียนรู้มาใช้ในร้าน",
    "educationText": "เราเรียนเรื่องการเขียน การบริหารร้าน และการสื่อสารกับลูกค้าผ่าน Baemin Academy กิจกรรม Baemin Friends ของกายองก็เป็นส่วนหนึ่งของการเรียนรู้อย่างต่อเนื่องนี้",
    "trademarkTitle": "ชื่อที่ออกแบบและจดทะเบียนเอง",
    "trademarkText": "กายองวางชื่อและโลโก้ ก่อนดำเนินการจดทะเบียนเครื่องหมายการค้ากายองอีเนด้วยตัวเอง เราจะค่อย ๆ ดูแลตัวตนและเรื่องราวของร้านต่อไป",
    "sinceNote": "SINCE 2012 บนโปสเตอร์หมายถึงปีที่แม่เริ่มทำงานด้านอาหารเกาหลี ส่วนกายองอีเนเปิดในปี 2022",
    "eventTitle": "เล่าให้เราฟัง\nถึงมื้อของคุณ",
    "eventText": "เมื่อมาที่ร้าน สอบถามพนักงานเกี่ยวกับกิจกรรมรีวิวใบเสร็จ Naver และสิทธิรับเครื่องดื่ม Coolpis ได้",
    "eventNote": "ไม่สามารถร่วมกับกิจกรรมอื่น โปรดตรวจสอบว่ากิจกรรมยังมีอยู่และสิทธิประโยชน์กับร้าน"
  },
  "ru": {
    "blog": "Читать другие истории Гаён",
    "learningTitle": "Опыт на кухне.\nИ место для нового.",
    "learningText": "Мы записываем мамины кулинарные приёмы, слушаем гостей и дорабатываем меню и повседневную работу. Учёба продолжается в жизни кафе, а не заканчивается сертификатом на стене.",
    "certAlt": "Сертификаты Baemin Academy и назначение Baemin Friends в заведении",
    "certCaption": "Документы об обучении в Baemin Academy и участии в Baemin Friends. Это не сертификаты качества еды.",
    "educationTitle": "Применять знания каждый день",
    "educationText": "В Baemin Academy мы изучаем тексты, управление кафе и общение с гостями. Участие Гаён в Baemin Friends — часть этого постоянного обучения.",
    "trademarkTitle": "Имя, которое создали и зарегистрировали",
    "trademarkText": "Гаён придумала название и логотип, а затем сама завершила регистрацию товарного знака Gayoungene. Мы продолжаем развивать облик и историю нашего кафе.",
    "sinceNote": "SINCE 2012 на плакате — год, когда мама начала работать с корейскими закусками. Gayoungene открылось в 2022 году.",
    "eventTitle": "Расскажите нам\nо своём обеде.",
    "eventText": "При посещении спросите сотрудников об акции с отзывом по чеку в Naver и напитком Coolpis.",
    "eventNote": "Нельзя совмещать с другими акциями. Действует ли предложение и какие бонусы доступны, уточняйте в кафе."
  },
  "id": {
    "blog": "Baca lebih banyak cerita Gayoung",
    "learningTitle": "Pengalaman memasak,\ndan ruang untuk terus belajar.",
    "learningText": "Kami mencatat pengetahuan memasak Ibu, mendengarkan tamu, lalu menyempurnakan menu dan pekerjaan sehari-hari. Belajar bukan hanya sertifikat di dinding, tetapi bagian dari kehidupan kedai.",
    "certAlt": "Sertifikat Baemin Academy dan penunjukan Baemin Friends di kedai",
    "certCaption": "Catatan pelatihan Baemin Academy dan kegiatan Baemin Friends, bukan sertifikasi mutu makanan.",
    "educationTitle": "Membawa pelajaran ke keseharian kedai",
    "educationText": "Melalui Baemin Academy, kami mempelajari penulisan, pengelolaan kedai, dan komunikasi dengan tamu. Kegiatan Baemin Friends yang diikuti Gayoung juga bagian dari proses belajar ini.",
    "trademarkTitle": "Nama yang dibuat dan didaftarkan sendiri",
    "trademarkText": "Gayoung merancang nama dan logo, lalu menyelesaikan pendaftaran merek Gayoungene sendiri. Kami terus merawat identitas dan cerita kedai ini.",
    "sinceNote": "SINCE 2012 pada poster menandai awal karier Ibu dalam memasak bunsik. Gayoungene dibuka pada 2022.",
    "eventTitle": "Ceritakan\npengalaman makan Anda.",
    "eventText": "Saat berkunjung, tanyakan kepada staf tentang acara ulasan struk Naver dan penawaran minuman Coolpis.",
    "eventNote": "Tidak dapat digabungkan dengan acara lain. Pastikan program dan manfaat yang tersedia kepada kedai."
  }
};
